### ISSUE TITLE
Make "Open all unread" button also mark the notifications as done

### ISSUE THREAD

**Issue by sindresorhus** [refined-github/refined-github#3068]
Either by default or as an alternative behavior when holding the Option key. It's annoying having to always manually click "Done" or checkmark on the notifications.

**Comment by fregante** [comment]
In short you want “reading” an issue to mean “finished” (Done)

You can already do this, but:
- you have to use **Save** if anything needs further work, *not* “Move to inbox”
- “read but not Done” issues will still be in the “All” inbox 

—

Now the problem you have is only a cluttered “All” inbox. This problem is unrelated to existing features (I mean this applies whether you “Open all unread” or open each one separately)

You could:
-  click “Open all unread” and then click “Mark all as Done” (you’re still on the same page)
- open the single item and then manually mark as Done in the following page

We could:
- Add a “Mark read as Done” button to clean the whole inbox regularly and painlessly
- Add a single-notification button or “alt click” feature to “open and Mark as done”

—

This setup has 2 advantages:
- if Read means Done, you no longer have to think about which ones are “read but unfinished” and which ones are “read and done”
- it works even on mobile: you can read anything and then on your computer just click “Mark read as Done”

**Comment by sindresorhus** [comment]
> click “Open all unread” and then click “Mark all as Done” (you’re still on the same page)

I have other read items I don't want to mark as done.

> open the single item and then manually mark as Done in the following page

That's what I'm doing, but it's annoying experience.

**Comment by sindresorhus** [comment]
> Add a single-notification button or “alt click” feature to “open and Mark as done”

👍

**Comment by fregante** [comment]
> I have other read items I don't want to mark as done.

Right, what I suggest is moving those to Saved instead. What do you think?

**Comment by sindresorhus** [comment]
Then I will forget about them.

I'm ok with differentiating read and done. I use the mobile app, read some notifications, but I cannot finish them on the phone, so when I get back to my computer they are read, I handle them, and then mark as done.
