### ISSUE TITLE
Keep checks visible while the commit title/description box is open

### ISSUE THREAD

**Issue by theasianpianist** [refined-github/refined-github#3435]
Would it be possible to allow users who are waiting for checks to succeed before merging (#975) to view the status of the checks while waiting? Right now the merge box is completely grayed out and there's no way to see how the checks are progressing.

**Comment by fregante** [comment]
Showing the checks while the merge form is open is possible, but I'm not sure if GitHub still updates the status since it expects it to be hidden.

It might look like:

<img width="923" alt="" src="https://user-images.githubusercontent.com/1402241/89483757-bc269c00-d794-11ea-8946-1842e2c964d6.png">

And we could show it if the user clicks the **first** "Merge button" while the checks are in progress.

**Comment by theasianpianist** [comment]
That would be cool. If GitHub doesn't update the status, how does Refined GitHub know when the checks are finished?

**Comment by fregante** [comment]
> how does Refined GitHub know when the checks are finished?

We look at the last commit pushed, which is always visible, not the "mergeability box".

**Comment by fregante** [comment]
Worth a try:

1. Force the mergeability box to be always `display: block`
2. Probably `scrollIntoViewIfNeeded()`

**Comment by fregante** [comment]
🎉 GitHub did it in https://github.com/refined-github/refined-github/issues/8123

<img width="937" alt="Screenshot" src="https://github.com/user-attachments/assets/1bb8c069-e35d-4949-8627-901abc9e4d17" />
