### ISSUE TITLE
Focus the topmost comment field in `quick-mention`

### ISSUE THREAD

**Issue by Geeyun-JY3** [refined-github/refined-github#3664]
When user is editing a comment and the comment field of that comment is focused, click the `quick-mention` button then insert the `@mention` to where the cursor is, instead of the bottom comment field.
When the comment field of that comment isn't focused, just do what this feature does now.

If this change is implemented, the tooltip should also be changed (not in a new comment).
URL: any issue and PR page, e.g. #3664

**Comment by notlmn** [comment]
Clicking on the `quick-mention` button would immediately make the text field you are on loose focus. So there is no way for us to know which text field on the page we have to go back to and insert the username as a mention.

I know that the auto-suggest feature of GitHub is not the best in the world, but that's the best thing you can get for quickly searching instead of scrolling around a bit and clicking on the `quick-mention` button.

**Comment by fregante** [comment]
GitHub does something similar when pressing the <kbd>r</kbd> key. From what I see, they will simply input the text in the first open textarea, regardless of focus. 

However it's buggy on PR reviews because they enter the text in the comment you're editing but _then_ they focus the new comment field.

---

We could try something similar:

1. Find the closest discussion (it could be a review thread or the whole issue discussion)
2. Find the first visible comment textarea inside it
3. Focus it, enter data

**Comment by fregante** [comment]
Last time I looked into this the logic was nuts and basically it's not really obvious where the user _wants_ this to appear. What if I clicked on a "Leave review comment" field but really I ignored it and went to leave a regular comment?

<img width="278" alt="workflow_2x" src="https://user-images.githubusercontent.com/1402241/217768482-ec3946e1-ed20-4d6c-b148-4d63724109f2.png">

**Comment by Geeyun-JY3** [comment]
> Last time I looked into this the logic was nuts and basically it's not really obvious where the user _wants_ this to appear. What if I clicked on a "Leave review comment" field but really I ignored it and went to leave a regular comment?
> 
> <img width="278" alt="workflow_2x" src="https://user-images.githubusercontent.com/1402241/217768482-ec3946e1-ed20-4d6c-b148-4d63724109f2.png">
> 

TBH I do not really understand. 
Do you mean that it is unnecessary for most users to implement this?

**Comment by fregante** [comment]
I mean it's not as straightforward as it sounds. Given a number of available fields, we can't safely guess where the user wants to add content. Even if we add further logic, we will break it for someone else. So now we have more code and still _undesired behavior_

**Comment by Geeyun-JY3** [comment]
So it means this bug just cannot be fixed. 
Fine.
