### ISSUE TITLE
backtick insertion within current selected text, includes trailling whitespaces

### ISSUE THREAD

**Issue by staabm** [refined-github/refined-github#4420]
backtick insertion of a current selected text, includes trailling whitespaces, which it shouldn't

repro
- while editing/creating a issue double click a word
- the double-clicked word get selected (including the trailling whitespace behind the word)
- press the backtick-key and refined github will sorround the selected word with backticks (including trailing whitespace)

example:
- a issue contains the text "the lazy fox jumps over.."
- double click the word 'lazy'
- press the backtick-key
- the resulting markup is "the `lazy `fox jumps over.." while it should be  "the `lazy` fox jumps over.." (spot the positions of the backticks)

reproduced in firefox 90a1 on windows10x64, with refined github 21.5.19.
also reproducible on chrome 93.0.4525.0  on the same machine

**Comment by fregante** [comment]
> * the double-clicked word get selected (including the trailling whitespace behind the word)

This might be a Windows-specific issue because I don't see it on macOS

> * the backtick-key and refined github will sorround the selected word with backticks (including trailing whitespace)

And this is a bug how? 😃 

If you select `hello `, you're asking the browser to wrap `hello `, not just `hello`. Doing otherwise would be wrong, I don't think most editors would try to be "smart" about that. 

Here's how it works in my Chrome, including when using the GitHub-native Bold shortcut:

![gif](https://user-images.githubusercontent.com/1402241/119985149-7ae5ce00-bfec-11eb-9119-0b7a363ff9c3.gif)

**Comment by staabm** [comment]
> And this is a bug how? 😃

I feel refined github could take this chrome/firefox glitches into account and trim the trailing spaces before sorrounding the selection with backticks

> Here's how it works in my Chrome, including when using the GitHub-native Bold shortcut:

your recording looks like I would expect it.

**Comment by staabm** [comment]
> If you select `hello `, you're asking the browser to wrap `hello `, not just `hello`. Doing otherwise would be wrong, I don't think most editors would try to be "smart" about that.

I can totally see, that this actually should be considered a browser bug.

**Comment by fregante** [comment]
> your recording looks like I would expect it.

I think you're referring to the word selection, because that's the only different part — and Refined GitHub can't change that.

> maybe its even a windows problem

Selecting the trailing whitespace appears to be a Windows behavior; Wrapping the exact selection is universal. Not a Refined GitHub problem, not GitHub’s, not Chrome’s, not Windows’.

**Comment by staabm** [comment]
> I think you're referring to the word selection, because that's the only different part — and Refined GitHub can't change that.

hm ok, when its not fixable we can close here.

thx for the insights.

**Comment by fregante** [comment]
You were onto something here! There's an exception: `\n`

![agif](https://user-images.githubusercontent.com/1402241/120298157-08c6ff00-c2f4-11eb-9414-c0e3a12da059.gif)

This feature however is handled by https://github.com/fregante/text-field-edit so any changes should be pushed to that repo.

**Comment by fregante** [comment]
> There's an exception: `\n`

That actually matches code editors and arguably it makes sense as an exception since <code>`</code> is used for code

This is VSCode:

![ko](https://user-images.githubusercontent.com/1402241/217798144-cf773fcf-5a2f-460a-b209-55717cad950f.gif)
