### ISSUE TITLE
Branches with multiple slashes aren't fully supported

### ISSUE THREAD

**Issue by KSH-code** [refined-github/refined-github#4492]
1. https://github.com/yakov116/TestR/tree/this/branch%2Fhas%2Fmany%2Fslashes
2. 
<img width="1051" alt="스크린샷 2021-06-18 오후 6 15 15" src="https://user-images.githubusercontent.com/29705162/122538129-35537880-d061-11eb-93be-9eca84a9d91f.png">

3. 
<img width="541" alt="스크린샷 2021-06-18 오후 6 13 51" src="https://user-images.githubusercontent.com/29705162/122537862-f4f3fa80-d060-11eb-86f3-ccc421090dc4.png">

The problem found from https://github.com/sindresorhus/refined-github/pull/4474
this is a task afterwards https://github.com/sindresorhus/refined-github/pull/4474

**Comment by fregante** [comment]
If the path has `%2F`, it's already not ambiguous and should not be passed to `disambiguateReference`

`a/b%2Fc` is unambiguously the name of the branch. Names won't have `%2F` in the filename (because it'd be represented as [`a/b%252Fc`](https://github.com/sindresorhus/refined-github/blob/branch/file%252Ffile) in the URL) and `/` cannot be part of the filename.

_Originally posted by @fregante in https://github.com/sindresorhus/refined-github/pull/4474#discussion_r652610916_

**Comment by yakov116** [comment]
We forgot about https://github.com/refined-github/refined-github/blob/1fd3bbb39a5e5eea712a7973fac1faa6ff5fef66/source/features/list-prs-for-branch.tsx#L18

Which is still broken for commit lists etc
