### ISSUE TITLE
Some features don't work on lazy-loaded comment forms

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#4542]
Also the upload button resurfaced by `minimize-upload-bar` is not showing.

1. Open any PR, like https://github.com/sindresorhus/refined-github/pull/4507
2. Start a review
3. Try to comment on the same thread

They appear when starting on a new thread, but not when continuing on an existing thread.

<img width="802" alt="Screen Shot 15" src="https://user-images.githubusercontent.com/1402241/124642779-6f72a600-deba-11eb-99ac-2716b2c5c9c0.png">

**Comment by cheap-glitch** [comment]
It seems this happens because the textarea and its associated toolbar don't exist on page load, they're first created when adding the review comment. Reloading the page makes this bug go away.\
The same thing happens with resolved review threads since they're lazy-loaded.

Using the additional `onNewComments` listener fixes it for resolved threads but not for new review comments. Should the listener be extended to cover this, or should we rely on some kind of observer instead?

**Comment by fregante** [comment]
> they're first created when adding the review comment

By who? Are they loaded together with the comment itself as a partial? Do you see any events that we can use in GitHub’s code? `onNewComments` seems unrelated (and as you mention it doesn't catch all cases) and `selector-observer` feels heavy, especially on a page that tends to get huge and already has trash performance on long PRs (especially on Safari)

We could potentially use `onElementRemoval` to track a submission and then look for the new form when that promise resolve, but this seem very fickle.

**Comment by kidonng** [comment]
It's not just review comments but regular comments too.
