### ISSUE TITLE
Extend `global-search-filters` to repository search results and Gists

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4665]
### Description

Right now `global-search-filters` only applies to global search results (`github.com/search`) but I feel it can be also useful in repository search results.

However some filters (Forks, Private) don't make sense there and we can add some new filters for code search, etc.

### Example URL

https://github.com/sindresorhus/refined-github/search?q=pagedetect

https://gist.github.com/search?q=tab

**Comment by fregante** [comment]
The global filters apply only to issues and PRs and we already add those to the regular issue and PR repo search

**Comment by kidonng** [comment]
I'm afraid we are not talking about the same thing. Are tout referring to `global-conversation-list-filters`?

**Comment by fregante** [comment]
Ugh yeah

**Comment by kidonng** [comment]
I just noticed this can also benefit Gists.

**Comment by fregante** [comment]
Closing because:

- the search page has been overhauled and gists will likely follow
- the feature will probably be dropped soon
- GitHub kind of added it:

<img width="288" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/205431857-e2192d2f-ee98-4ba0-8db0-d7c7eec42a85.png">
