### ISSUE TITLE
`shorten-links` conflicts with OctoLinker

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#4758]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

It seems [OctoLinker](https://github.com/OctoLinker/OctoLinker) will linkies the code and `shorten-links` kicks in, potentially making the code invalid.

Worth noting that OctoLinker also linkies code blocks in (Markdown) documents (e.g. https://github.com/oakserver/oak#application-middleware-and-context), but Refined GitHub doesn't process those links.

### Screenshot

![image](https://user-images.githubusercontent.com/44045911/132124457-0c63e6c4-d1ff-4a80-810a-1b740851291f.png)

Note the `https://` prefix is stripped

### Example URL

https://github.com/oakserver/oak/blob/main/deps.ts

### Browser(s) used

Chrome

**Comment by fregante** [comment]
This must be due to a recent change… this is a grave bug and it happened in the past. Shorten links cannot be applied to links in code blocks, there used code to avoid this situation.

**Comment by kidonng** [comment]
Now that you mentioned I remembered it as well, however the feature itself has not changed much, possibly it's one of the dependencies.

**Comment by kidonng** [comment]
This seems to reappear:

- https://github.com//denosaurs/mod.land/issues/55
  
  <img width="365" alt="image" src="https://user-images.githubusercontent.com/44045911/156889403-de0f23c1-a8fa-4835-ab1b-0223ee59ca74.png">

- https://github.com/oakserver/oak#application-middleware-and-context
  
  <img width="496" alt="image" src="https://user-images.githubusercontent.com/44045911/156889410-d3663524-8ba9-4c28-b8f6-3e72dddaed6e.png">

**Comment by fregante** [comment]
You're right. I'm not seeing it in Safari but I see it in Chrome. Maybe this was caused by the latest release and would warrant a release as soon as fixed.

**Comment by fregante** [comment]
I think it's because both OctoLinker and RGH are linkifying that URL and then `shorten-links` will shorten OctoLinker’s link. It just depends on who gets there first:

<img width="678" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/156891513-cb847f2e-9392-4a26-8a3e-84453bfe7aeb.png">


<img width="472" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/156891505-07ffde81-781b-4ba6-b27b-be610e4327d0.png">


1. **Quick fix: Also exclude `.octolinker-link`**
2. Second fix: If we get to it after OctoLinker, then we should ignore it in `linkify-code`
3. OctoLinker fix: If it finds a Refined GitHub link, it should replace it
