### ISSUE TITLE
The default submit action of PR review form isn't "Approve"

### ISSUE THREAD

**Issue by slaweet** [refined-github/refined-github#5010]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
![Screenshot from 2021-10-29 15-18-34](https://user-images.githubusercontent.com/1254342/139442335-eb76579f-445d-4273-997a-727482738858.png)

- [ ] Console errors, if any

### Description

The green "Approve" button in the PR review dropdown form visually looks like the primary call to action. However, if I submit the form with ctrl+enter it uses the "Comment" button instead.

It happened to me so many times that I made a "Comment" instead of "Approve" that I think the UI is just wrong.

I can imagine two solutions:
- Change the visual look of the buttons, so that "Comment" looks like the primary call to action
- Change the form default submit action (used when ctrl+enter) to be "Approve"

### Example URL

https://github.com/refined-github/refined-github

### Browser(s) used

Google Chrome Version 95.0.4638.54 (Official Build) (64-bit)

**Comment by kidonng** [comment]
> > * Change the visual look of the buttons, so that "Comment" looks like the primary call to action
> 
> However I do like this 😃

To me this is a bug for real, only the primary action should have the primary style/background. We should not "induce" people to approve things.

> Maybe the "request changes" should also be _not red_

That's also welcome, the red text looks like a potentially destructive action while in fact it isn't.

**Comment by slaweet** [comment]
> That's GitHub’s own behavior, not Refined GitHub’s bug:
> 
> <img alt="Screen Shot" width="665" src="https://user-images.githubusercontent.com/1402241/139465368-aad4f56e-ea65-4633-a43f-80e1bd4d05be.png">

I think it is Refined GitHub’s bug, because in GitHub's original UI it's IMO very clear what ctlr+enter will do.

**Comment by moussetc** [comment]
Welp, I hugely regret the UI change caused by this issue. Now I click on Comment instead of Approve (which is the button I want 95% of the time, because I rarely leave comments via this popup since I put comments directly on files or via the main page). 
I also regret no more red for blocking changes. Sure, it's not a _destructive_ action but it's an impactful one and the red button was thematic with the red PR status when changes are requested.

Anyway, I'm aware my opinion will change nothing but 🤷 

(still loving the plugin though, thanks for your work on trying to make a usable interface out of GH)

**Comment by fregante** [comment]
I think moving the "Comment" button in the place of the "Approve" button might have been a mistake because visually very little changed, so mouse users will keep clicking the green button expecting it to be "Approve"

@refined-github/maintainers worth using hotfix.css to keep the "Comment" to the left as soon as possible? We can't push a new version already

**Comment by cheap-glitch** [comment]
> I also regret no more red for blocking changes

@moussetc There should be a red icon next to the button text though? If you can't see it then that's a bug.

> worth using hotfix.css to keep the "Comment" to the left as soon as possible?

You mean keeping all the buttons on the right put changing the order? In that case it should probably be (from left to right) "Comment", "Approve", "Request changes"; to match with the native (vertical) order.

**Comment by moussetc** [comment]
> @moussetc There should be a red icon next to the button text though? If you can't see it then that's a bug.
@cheap-glitch 
It's not red here (Github Enterprise):
![image](https://user-images.githubusercontent.com/8834237/139910250-df229845-3ee1-4afa-b8e3-b034bc3fa6f0.png)

**Comment by cheap-glitch** [comment]
> Though I do see the button colors on plain old Github.com

Ah yes, that's probably because we only used the new color classes, so they have no effect (yet) on GHE :sweat_smile:

**Comment by keith** [comment]
![image](https://user-images.githubusercontent.com/283886/139920326-c3345acd-381d-46b7-9e29-bea61184af0c.png)

Looks like that CSS fix results in this for me

**Comment by kidonng** [comment]
I think there are two issues here:

- GitHub's primary button is "submit" which doesn't mean anything by itself. Buy we (mistakenly) made one of the three actions ("comment") stand out which do have implied meaning, and that's what we are avoiding in the original PR (even if the action is neutral). We didn't realize this in time though.
- About the location of the buttons: I do think we need to indicate what the primary action could be (and that's why we give the comment button a primary background), and putting the primary button on the right is what GitHub does. 

Therefore I suggest removing the background of comment button but keeping the location/order. Thoughts?

**Comment by fregante** [comment]
Green = default. That part is fine. It’s the change of order that’s confusing. We can use that hotfix to revert it

**Comment by fregante** [comment]
Hotfix added. 

<img width="682" alt="Screen Shot 14" src="https://user-images.githubusercontent.com/1402241/140034625-14422806-b331-404d-91a4-879d1338e8b8.png">

PR welcome to fix the order on `main`

**Comment by tonglil** [comment]
Is there a way to give the currently unused `cmd+shift+enter` keyboard shortcut to "approve"?

- `cmd+enter`: comment
- `cmd+shift+enter`: approve

**Comment by fregante** [comment]
Please open a new issue
