### ISSUE TITLE
Handle blocked users better than GitHub does

### ISSUE THREAD

**Issue by piegamesde** [refined-github/refined-github#5050]
### Description

As you may know if you ever blocked a person, GitHub's realization of that feature is pretty insufficient. Especially, we can still interact "normally" on a common organization's repository.

While Refined GitHub cannot prevent other (=blocked) people from commenting, it could improve the situation in the following ways:

- At least mark comments from blocked people as such, maybe even automatically hide them
- Print a warning when interacting with a thread where there also is a blocked person

### Screenshot

![image](https://user-images.githubusercontent.com/14054505/140588691-79803d7f-9761-40a5-a86a-a3c81eb17d5b.png)
![image](https://user-images.githubusercontent.com/14054505/140588701-ec75d431-3eb1-4968-95a3-a71f38f7b749.png)

### Example URL

https://github.com/NixOS/rfcs/pull/98#issuecomment-962035976

**Comment by fregante** [comment]
Agreed. We could:

- fetch the list of blocked users weekly
- clear it manually when we detect a "blocked" click, so it updates again
- detect the comments in issues and PRs, and make them less visible, for example with a small font and lower opacity of the whole block. Hiding them altogether means we also need to provide a UI to unhide them, which I'd rather not do

**Comment by piegamesde** [comment]
If making interactive UI is too much, I think simply styling the header bar in a red-ish color and adding "**(blocked)**" to the display name would do just fine. Or, how about adding a box to the top right next to "member"/"contributor"/… ? Quick mock-up with devtools (it's ugly, I know):

![image](https://user-images.githubusercontent.com/14054505/140610309-d47ca8ee-8a2a-42a4-8487-a1328d900aff.png)

Regarding the font size, I'd prefer to gray out the text. I've already seen this as a moderation tool for comment sections where a comment should be marked as "disapproved" without being deleted and I think it works quite well.

**Comment by kidonng** [comment]
> Hiding them altogether means we also need to provide a UI to unhide them

Maybe we can abstract the logic from `hide-low-quality-comments`, which would also be useful to #5118.

**Comment by fregante** [comment]
I don't think this is particularly worth it or it's even counterproductive:

- hiding comments will inevitably lead to "who said that?" or "X already said that" when replying to such thread, so we can't quite hide them safely. This is ok on Twitter where tweets don't matter, but on GitHub this just lengthens discussions
- marking comments with "blocked" doesn't seem particularly productive as the comment is still there and now you're also drawn to it thanks to its shiny red label. Either way you're going to read it
- using `hide-low-quality-comments`’ UI isn't great either because you'll likely be tempted to _check out what this moron wrote_, defeating the purpose of the feature. I know I do that with `hide-low-quality-comments` even fully-knowing that the comment is 100%-certainly completely useless 😅 


If you're looking to hide specific users, I suggest this:

<details>
<summary>Example code</summary>


From https://github.com/refined-github/refined-github/issues/4808#issuecomment-1206224179

```css
/* Collapse comments by @github-actions #5050 */
.timeline-comment:not(:hover):has(.author[href="/apps/github-actions"]) {
	overflow: hidden;
	height: 100px;
	opacity: 50%;
}
```

![text](https://user-images.githubusercontent.com/1402241/183043547-62f9192c-7c8e-4383-98cf-86688e317fa7.gif)


</details>
