### ISSUE TITLE
Apply markdown syntax highlighting to raw PR comment

### ISSUE THREAD

**Issue by JoshuaSCochrane** [refined-github/refined-github#5075]
### Description

Having the pr template rendered in plaintext is confusing for people new to markdown, especially if it includes comments describing what to put in various fields. It would be great if GitHub formatted the pr comment box (at least the initial one) using markdown syntax highlighting, so the comments/headings/bullets/etc. would be more clear.

Should appear on any new/edited PR comment.

### Example URL

https://github.com/refined-github/refined-github/pull/5074

**Comment by kidonng** [comment]
> Having the pr template rendered in plaintext is confusing for people new to markdown

I don't want to be arrogant but it's their duty to learn Markdown. GitHub offers [Markdown guides](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) for new users and it takes less than 10 minutes to grasp the basics.

> especially if it includes comments describing what to put in various fields

This is valid though, I myself find some templates contain too much unnecessary comments/info. But again, it's an issue with those who create the templates.

> It would be great if GitHub formatted the pr comment box (at least the initial one) using markdown syntax highlighting, so the comments/headings/bullets/etc. would be more clear.

That ship sailed a long time ago. We are not going to mess around with the comment box with syntax highlighting, which numerous people tried and failed due to GitHub updates or edge cases that are not so edgy.

**Comment by JoshuaSCochrane** [comment]
Fair enough.

Several of the devs on the team are 'seasoned', but still new to git/GitHub/markdown/etc. _in general_, and we are geographically separated, with language and cultural differences as well, so anything we can do to ease the burden as they come up to speed is helpful. We tried adding comments to the template as guides, but without syntax highlighting in PR creation, it probably does just add noise. I've tried getting them to use the Preview more, and will continue to demonstrate and suggest that when I can.

Thanks for consideration and I understand the challenges involved. I guess I wasn't sure if there was an easy way to apply the [very basic, but better than plaintext] syntax highlighting GH already provides when editing a markdown file to the comment box itself, but I guess it's not so straightforward, so I'll close this one out.

**Comment by kidonng** [comment]
No worries! You can also send a request at https://github.com/gihub/feedback/discussions

**Comment by 0xdevalias** [comment]
Just wanted to add a little note here for anyone else who would like to see syntax highlighting in GitHub's markdown fields; a super neat browser extension lets you work around this to use a local IDE (which should have markdown syntax highlighting) for manipulating the contents of a text field within the browser:

- https://github.com/fregante/GhostText
  - > Use your text editor to write in your browser. Everything you type in the editor will be instantly updated in the browser (and vice versa).

**Comment by nedtwigg** [comment]
I just released an Apache2 browser extension which does syntax highlighting in all GitHub comment fields (issues, prs, etc.) https://github.com/diffplug/gitcasso?tab=readme-ov-file#screenshots

I have enjoyed having it because I can see my mistakes easier (mismatched link brackets, etc).

> We are not going to mess around with the comment box with syntax highlighting, which numerous people tried and failed due to GitHub updates

It is quite a moving target, issues on the project board in particular were kinda tricky. I would not have even tried to keep it working a couple years ago, but AI makes it pretty easy. We have an update pipeline using Claude Code combined with Playwright to keep it up-to-date semi-automatically.
