### ISSUE TITLE
Redirecting to #3543 after installing is great but can be better

### ISSUE THREAD

**Issue by simkimsia** [refined-github/refined-github#5080]
### Description

I am new user.

I was directed to #3543 after installing which is awesome.

Less awesome is i tried to create teh PAT myself but unsure why scopes to give.

Turns out under extension options > there's a generate link that automatically does that for you

## Recommendation  

Show the screenshot to the extension option so new users know how to generate the PAT and place it in the options. Put the screenshot inside the description of #3543

### Screenshot

![CleanShot 2021-11-17 at 12 48 23@2x](https://user-images.githubusercontent.com/245021/142136661-d162fa20-b099-48c2-b2fe-64db841b12cc.png)

### Example URL

https://github.com/refined-github/refined-github/issues/3543

**Comment by fregante** [comment]
Adding a screenshot might be slightly confusing because people could think that it's not a screenshot but the actual field. I'd probably linkify "in the extension's options" so that you can visit it directly. 

To do so we need a meta feature that creates such link on load because `chrome-extension://` links don't work on the web (and we also have to support multiple browsers)

**Comment by simkimsia** [comment]
Linkify is nice but if you put a screenshot in #3543 with the high light I used people will know that's a screenshot.

Did I understand your concern correctly?

**Comment by fregante** [comment]
I don't see how a screenshot helps more than a plain link on the instruction itself. The screenshot is not actionable and it's better to just follow the link to see the same thing.

**Comment by simkimsia** [comment]
I totally agree with you a link is better than screenshot.

I'm saying a screenshot is better than no screenshot and no link which is the status quo
