### ISSUE TITLE
`clean-repo-sidebar`: Drop new duplicate information from repo sidebar

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5179]
### Description

Related:

- https://github.com/refined-github/refined-github/issues/5164

### Screenshot

<img width="472" alt="Screen Shot 12" src="https://user-images.githubusercontent.com/1402241/145553868-8598dfbd-b882-42cf-9824-51a85789f91a.png">

### Example URL

https://github.com/refined-github/refined-github

**Comment by kidonng** [comment]
`repo-age` now seems to have a larger top margin than GitHub's native list items (`.mt-3` v.s. `.mt-2`). IMO it should be handled together if anyone wants to fix this issue.

**Comment by fregante** [comment]
> now seems to have a larger top margin than GitHub's native list items

Once we drop those 3, it'll be fine again because "18 tags" has the same spacing

**Comment by kidonng** [comment]
I just calling them "duplicate info" is not 100% correct because they used to be [these links](https://web.archive.org/web/20211207124618/https://github.com/refined-github/refined-github): 
<img width="404" alt="截屏2021-12-12 20 59 59" src="https://user-images.githubusercontent.com/44045911/145713373-fcee7e9b-7c38-4e3b-b450-62fbb562e6a1.png">

**Comment by fregante** [comment]
Ugh, right. So we can leave them and:

- restore `hide-watch-and-fork-count`, without the logic "to show the watcher count"
- reduce the spacing of `repo-age` as mentioned earlier
