### ISSUE TITLE
Show Merged PR count

### ISSUE THREAD

**Issue by Dentrax** [refined-github/refined-github#5241]
### Description

I am not sure whether it's intentional since we have to do additional API request to _get merged prs_. We can add a new feature-flag for this and make it _false_ by default. It's a simple trade-off, if we enable this option, then the page will load slightly slower.

![Screen Shot 2021-12-23 at 15 29 25](https://user-images.githubusercontent.com/16493751/147240762-fbc1d05d-7639-411b-bc1c-e8a16df58f90.png)

Currently, we need to click _Merged_ button to get merged count as follows:

![Screen Shot 2021-12-23 at 15 29 38](https://user-images.githubusercontent.com/16493751/147240783-d066c487-4632-4ef6-919c-dfe15b1cba8b.png)

### Screenshot

Like `Merged (%d)`

![Screen Shot 2021-12-23 at 15 31 08](https://user-images.githubusercontent.com/16493751/147240925-3d01699b-9147-4e5a-a96d-63c5d3e6387d.png)

### Example URL

https://github.com/refined-github/refined-github/pulls

**Comment by cheap-glitch** [comment]
> We can add a new feature-flag for this and make it _false_ by default.

We don't add options or flags to features, and we don't make things disabled by default. It has to make sense for most users.

> It's a simple trade-off, if we enable this option, then the page will load slightly slower.

I don't think it's worth it. If we cache the call, the number will be unreliable or imprecise because it always might be outdated, which makes it pointless imo. If we don't cache it, that means a lot of requests to the API, for something you don't really need that often (and can get with a click or two).

Maybe we could get it from the DOM when the user visits the list of merged PRs, and then use that value for the rest of the navigation. But again it will probably be outdated fairly quick.

**Comment by fregante** [comment]
The request makes sense, but we'd rather not make an extra HTTP request for this. It basically cannot be cached since it depends on the query itself (as well as time).

**Comment by kidonng** [comment]
__Impossible tag__

**Comment by fregante** [comment]
> _"impossible" tag_

We need a "http 503" tag 😅
