### ISSUE TITLE
"Forked-to" feature not working

### ISSUE THREAD

**Issue by casperklein** [refined-github/refined-github#5277]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Example URLs

This happens on all repos I've forked.

### Browser(s) used

Firefox 95.0.2

### Description

I noticed, that since a few weeks the "forked-to" feature does not work anymore, . Can someone confirm this?

I am using version 21.12.12 of this addon.

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by cheap-glitch** [comment]
This was fixed in [`21.12.21`](https://github.com/refined-github/refined-github/releases/tag/21.12.21), but for some reason it failed to be released on AMO, so Firefox users can't update to the latest version.

You'll have to wait for the next release, which will probably happen at the end of this month.

**Comment by fregante** [comment]
22.1.11 will be available on the stores today 

https://github.com/refined-github/refined-github/releases/tag/22.1.11
