### ISSUE TITLE
`preview-hidden-comments` stopped working on review comments

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5286]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Example URLs

https://github.com/refined-github/refined-github/pull/5281#discussion_r780786267

### Browser(s) used

Chrome

### Description

![image](https://user-images.githubusercontent.com/44045911/148697645-76b95f31-35a1-4a76-b726-423bb7319035.png)

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by cheap-glitch** [comment]
This is not a bug, it's a limitation caused by the lazy-loading of minimized review thread comments in a resolved thread.

If you look at the DOM you'll see it's just a wrapper around an `include-fragment`, so the feature can't pull out the comment contents.

More details in https://togithub.com/refined-github/refined-github/pull/4915
