### ISSUE TITLE
`one-click-diff-options` doesn't apply as default

### ISSUE THREAD

**Issue by karlhorky** [refined-github/refined-github#5288]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Example URLs

https://github.com/depcheck/depcheck/pull/656/files

### Browser(s) used

Chrome macOS latest

### Description

It seems the diff default option is not set when using the `one-click-diff-options` buttons:

1. Click on the "unified diff" button when the default has already been set to Split diff
2. Refresh the page
3. The Split diff appears again

On the main GitHub website (with the "Diff view" dropdown), it does two requests - one POST and one GET.

Maybe the extension is not sending the first POST request?

<img width="261" alt="Screen Shot 2022-01-10 at 10 12 08" src="https://user-images.githubusercontent.com/1935696/148741631-9ad60e0b-10b1-4049-87eb-a027dea83d59.png">

<img width="689" alt="Screen Shot 2022-01-10 at 10 10 18" src="https://user-images.githubusercontent.com/1935696/148741536-e4481230-95fd-4957-a553-cbe30851bdaf.png">

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

**Comment by kidonng** [comment]
Thanks for the report! This has been mentioned in https://github.com/refined-github/refined-github/issues/5009#issuecomment-955113121.

**Comment by fregante** [comment]
_once again it's haappeeniiiiing_

@kidonng I think this kinda classifies as a bug since we're breaking GitHub’s default behavior. It appears that the content of that dropdown is not loaded later, so we can "easily" use `await pushForm(select('diffview')) && location.reload()`. If the form is missing we can just let the regular link through and log an error to the console so that the feature doesn't stop working.

**Comment by fregante** [comment]
Thanks for reporting back!
