### ISSUE TITLE
Notifications view: List Organizations between Filters and Repositories

### ISSUE THREAD

**Issue by IanButterworth** [refined-github/refined-github#5311]
### Description

On the notifications page the left bar currently has "Filters" and "Repositories" for filtering.

It would be helpful to show a consolidated list of organizations in the same way, with counts, so you can filter notifications by organizations.

Because the list of organizations would be at longest the same length, or in most cases much shorter, than the list of repos, I think it could go in between Filters and Repositories. 

### Example URL

https://github.com/notifications

**Comment by cheap-glitch** [comment]
Showing a permanent list of org filters in the sidebar is easy enough, after all they're just links to `https://github.com/notifications?query=org%3<org name>`.

But displaying an accurate notifications count is much more tricky, as it would basically mean an API call for each org, every time the notification page is loaded. (Not to mention the API might not even be able to give us that data.)

So unless there's a convenient workaround, I'm afraid this might be too much for RGH. Let's see what the other maintainers think though :)

**Comment by kidonng** [comment]
There's also this question: where should "Organizations" be?

- Below "Repositories"? Then it would be hard to reach if you have notifications coming from lots of different repositories.
- Above "Repositories"? Then the situation is reversed, "Repositories" would be hard to reach if you have joined many organizations. Remember we can't hide empty orgs since there's no available data.

If you argue you only need access to a few organizations, then you can already do this today: use custom filters provided by GitHub.

**Comment by fregante** [comment]
> But displaying an accurate notifications count is much more tricky, as it would basically mean an API call for each org, every time the notification page is loaded.

Correct.



> Showing a permanent list of org filters in the sidebar is easy enough, after all they're just links to `https://github.com/notifications?query=org%3<org name>`.

Without counts, this is just a fixed list of links — browser bookmarks can already do that.
