### ISSUE TITLE
Saved searches

### ISSUE THREAD

**Issue by rasmusbe** [refined-github/refined-github#5316]
### Description

I would like a feature to save searches to reuse them later. It would be helpful when using complex searches in issues / pull requests.

### Screenshot

Mocked save button
![image](https://user-images.githubusercontent.com/2124386/149774160-5731c443-9156-4458-95ec-d74401a9e043.png)

Set the search filter name
![image](https://user-images.githubusercontent.com/2124386/149774182-9eaf4f77-a872-4fdc-8abb-b2c9e2737b7f.png)

Re-use it from the drop down (maybe add a edit / delete button or something)
![image](https://user-images.githubusercontent.com/2124386/149774207-0b92bd67-5b64-4105-9c06-525a6f28cb17.png)

### Example URL

https://github.com/home-assistant/core/issues?q=sort%3Aupdated-desc+label%3A%22integration%3A+sonos%22%2C%22integration%3A+zha%22%2C%22integration%3A+icloud%22+is%3Aopen

**Comment by fregante** [comment]
This would be useful and I thought about making an extension for it in the past, but unfortunately it doesn't belong to Refined GitHub because we effectively never save any user data nor any feature has any options.

**Comment by kidonng** [comment]
This reminds me GitHub Mobile app remembers your last search queries for issues and PRs (but they do not share the same query). I wonder if we can port that to the web.

**Comment by kidonng** [comment]
GitHub Mobile app recently also introduced "Shortcuts", which is essentially saved searches (for issues, PRs and discussions). However it seems to be the job for a separate extension (and I wonder if such extension already exists?)

**Comment by fregante** [comment]
> your last search queries for issues and PRs (separately). I wonder if we can port that to the web instead.

Useful there but it sounds troublesome as an extension. We already change the sorting by default and I'm surprised there hasn't been a big pushback on that one (but I guess it's because it does make sense to many)

> You can consider the saved queries "caches" 

I see no advantage in using caches for a setting we don't want to lose. We can use the chrome storage API directly if we wanted.  webext-options-sync is fine since we have it. 

> GitHub Mobile app recently also introduced "Shortcuts",

I'm not interested in specific global shortcuts because, ahem, browsers have bookmarks already, unlike the app. 😅 

This request works because those filters could be shared across repos. Technically we could extend the existing filters feature and default it to the 2 filters we currently add. 

The only thing I foresee is people asking to make filters per-repo and that obviously isn't going to happen (as it crosses another "rule" for features)

**Comment by yakov116** [comment]
> This would be useful and I thought about making an extension for it in the past, but unfortunately it doesn't belong to Refined GitHub because we effectively never save any user data nor any feature has any options.

👍 

> Technically we could extend the existing filters feature and default it to the 2 filters we currently add.

Where is the user setting that (not that I think its a good idea to extend features like that)


IMHO this should be its own extension

**Comment by kidonng** [comment]
> The only thing I foresee is people asking to make filters per-repo and that obviously isn't going to happen (as it crosses another "rule" for features)

You forgot sorting and filtering of filters 😁

**Comment by fregante** [comment]
Let's extend `more-conversation-filters`


> we could extend the existing filters feature and default it to the 2 filters we currently add.

The storage can be handled via a raw `browser.storage.sync.*` call, not `webext-options-sync` since this won't be shown in there.

**Comment by gsingh93** [comment]
I found this extension recently: https://chrome.google.com/webstore/detail/github-saved-filters/pmkbippobcmchabghaeonfbbcncjhmjm/related?hl=en

It seems to work well, but I wasn't able to find the source code for it, so maybe it's not open source. But it could be used as a model for how the UI and functionality could work. And if it turns out to be open source, it might be better to just ask the author if they could contribute to this repo.

**Comment by fregante** [comment]
That UI is too complex for us, we can't have huge single features because we already have 200 other features to take care of.

**Comment by fregante** [comment]
Too many feature requests, realistically we’ll never get there. I’m closing those I think aren’t worth it. If it was accepted before, I may still accept a PR in the next 6 months.

**Comment by fregante** [comment]
Save searches are available in the global search: 

<img width="780" alt="Screenshot 4" src="https://user-images.githubusercontent.com/1402241/224503035-d23f8bc9-7163-45b3-9851-fd9201cb3da7.png">

<img width="337" alt="Screenshot 5" src="https://user-images.githubusercontent.com/1402241/224503095-2482e8ec-007e-4465-9330-c88780f00ee4.png">


Hopefully they'll bring the search improvements to the issue lists as well (although I can't way I'm exited about getting a new React view there…)

**Comment by fregante** [comment]
Also there's an extension that implements exactly this on repo searches: https://chrome.google.com/webstore/detail/github-saved-filters/pmkbippobcmchabghaeonfbbcncjhmjm?hl=en
