### ISSUE TITLE
Hide successful ci activity notifications

### ISSUE THREAD

**Issue by steveoh** [refined-github/refined-github#5358]
### Description

I get a lot of notifications for successful github action workflow runs. These notifications don't seem to be something I can turn off. I really only care about workflows that failed as that indicates that I need to take action. The successful runs clutter up the notification center and I think they would be best to be auto dismissed.

The feature request is to auto dismiss successful ci runs when viewing the notification center page.

### Screenshot

![image](https://user-images.githubusercontent.com/325813/152007299-e92cf6f5-b2f9-4865-8716-0c5a9b1ad60d.png)

### Example URL

https://github.com/notifications?query=is%3Aunread

**Comment by cheap-glitch** [comment]
This is already available :smiley:

Go to https://github.com/settings/notifications and under "Actions", check "Send notifications for failed workflows only".

**Comment by steveoh** [comment]
![thank you](https://media.giphy.com/media/PO62ODuFN8Y1jbMbgi/giphy.gif)

**Comment by steveoh** [comment]
Hmm, this got recent recently. Maybe from an update?

**Comment by fregante** [comment]
Here's the problem with notifications from Refined GitHub's standpoint:

- RG cannot "mark as done" user notifications for everyone just because some dislike them, it'd be a destructive action
- RG can't have features ["disabled by default"](https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#2-it-makes-sense-as-a-default-for-everyone)
- RG can only see them when you open the notifications page, and at that point you've already been bothered by the blue circle
- RG can't regularly fetch the notifications to filter them as that would trigger relatively too many HTTP requests. There are dedicated extensions for this (I'm not say that they would be good candidates for your suggestion though)
  - https://github.com/tanmayrajani/notifications-preview-github
  - https://github.com/sindresorhus/notifier-for-github
