### ISSUE TITLE
Suggest length limit for PR titles

### ISSUE THREAD

**Issue by karlhorky** [refined-github/refined-github#5375]
### Description

The `suggest-commit-title-limit` suggests the length of a commit title when a PR is about to be merged.

It would be nice to have a length warning also during creation and editing of the PR (the title field at the top of the page), to warn as early as possible and make it easier to merge things later (could also be a default-off option)

### Example URL

https://github.com/refined-github/refined-github/pull/5365

**Comment by fregante** [comment]
This already kind of happens if your window is large enough, the field is sized to fit exactly the limit, so you know how many characters are left by just treating the field as a progress bar:
![gif](https://user-images.githubusercontent.com/1402241/166138214-adf39150-3a2b-469d-9ec8-c03309d27eb5.gif)

However it's slightly off currently:

- https://github.com/refined-github/refined-github/issues/3998

**Comment by cheap-glitch** [comment]
@fregante I think the feature request is about extending `suggest-commit-title-limit` to the "Compare" page and the conversation header (when editing the PR title).

**Comment by karlhorky** [comment]
Yes, sorry if that was unclear, I meant during creation and editing of the PR, not during merge.

**Comment by fregante** [comment]
Ahhh no it's not you, it's me, I must have been high on caffeine. 

The PR title limit is only a consequence of the **commit** title limit, which we kind of backport to the PR title with our other feature. I don’t think that exposing this limit when writing a PR title makes sense though:

1. The PR title is too long
2. Because the commit title is limited to 72 characters
3. And there's a feature that *maybe* will **suggest** shortening the commit title
4. And _maybe_ the _maybe-changed_ commit title will be set as a PR title

**Comment by karlhorky** [comment]
Ok, not sure I completely understand all of the details written above, but if I'm understanding correctly I guess the gist of it is:

"we already have a limit when squash merging, and having a limit in other cases often doesn't make logical sense"

**Comment by fregante** [comment]
More like "The PR title does not have a limit; the length only ever comes into play in a very specific set of circumstances that happen much later"

**Comment by karlhorky** [comment]
So I keep coming back to this, since some kind of feature would be a huge help to workflows with squash merging.

Eg. consider this situation:

1. A team is using squash merging
2. A team wants to know as early as possible about possible errors, not when they are in the process of merging

For this use case, I would be great to have an error earlier in the process.

Is it possible to detect squash merging and enable for this use case?

Or, another alternative which would also work: add a floating character counter in the input of the PR title during pull request creation, so that someone can just visually verify this, if it fits their workflow.

@fregante @cheap-glitch thoughts?

**Comment by fregante** [comment]
Reopened on the basis that super-long PR titles aren't exactly ideal either, however we can't show a red color in this case, maybe an orange or yellow is better if available. 

A character count wouldn't be particularly helpful because it cannot/does not include the PR number `" (#123)` so: at what magic number do you have to stop on the PR `#123`? It's not 72, not 70, not 68, etc… so we need to use a similar logic to the commit title, except we silently subtract `" (#123)".length` from the total.
