### ISSUE TITLE
Infinite scroll on pull requests and issues

### ISSUE THREAD

**Issue by Milo123459** [refined-github/refined-github#5421]
### Description

The infinite scroll for the news feed, but on issues & pull request pages. The pagination option would still be there but would be moved elsewhere so that you can still access it.

### Example URL

https://github.com/vercel/next.js/pulls

**Comment by cheap-glitch** [comment]
Infinite scroll makes sense on the newsfeed because it's a stream of "disposable" events, but imo it's absolutely _terrible_ for lists of items that are meant to be regularly browsed. Even if the pagination buttons are still present (where?), you'd be fighting against the auto-loading constantly.

Then again, if I'm in the minority here I can always disable the feature, so I guess I'm -0.

**Comment by Milo123459** [comment]
This is just a niceity that I think... would be nice. I like scrolling through PRs to check status' and just overlook things, and having an infinite scroll for it just makes it a little bit easier.

**Comment by yakov116** [comment]
It would not be possible without fetching and recreating the entire dom.

**Comment by Milo123459** [comment]
Well in that case, it's not worth it.

**Comment by kidonng** [comment]
You might be interested in https://github.com/machsix/Super-preloader
