### ISSUE TITLE
`forked-to`: Cannot set properties of undefined (setting 'href')

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5435]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

Just browse around https://github.com/refined-github/refined-github and you will see it in the console

### Extension version

22.2.22

### Browser(s) used

Chrome

### Description

```
TypeError: Cannot set properties of undefined (setting 'href')
    at init (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:7691:91)
    at async runFeature (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:3045:20)
    at async setupPageLoad (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:3055:34)
```

Seems related to #5417. Actual feature is not broken, just some weird error.

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

**Comment by fregante** [comment]
Fixed in my PR.

The issue was that we add **and expect** a relative `href` attribute (`/user/repo/page`) but `sort-conversations-by-update-time` sets the `href` to a full URL.

https://github.com/refined-github/refined-github/blob/f32792489d8ce1f7c404346916f8697d882421e5/source/features/sort-conversations-by-update-time.tsx#L28
