### ISSUE TITLE
Exclude disabled features from "Find feature" steps

### ISSUE THREAD

**Issue by karfau** [refined-github/refined-github#5442]
### Description

I was using the awesome "Find Feature" button to figure out why in my list of PRs and issues some are grey.

It explained to me that the issue was coming form `dim-bots`, but when I checked, it was already disabled. Luckily I discovered `dim-visited-conversations` along the way since I only searched for `dim`, so I was abe to disable it.

But I wonder why the it even suggests features that are disabled...

I think it could also be considered a bug, but the form for that didn't seem to fit.

Steps to reproduce:
1. Disable `dim-bots` and enable `dim-visited-conversations`
2. Open any list of PRs or issues where you can see some title being dimmed and others aren't (the link I added works for me but might not work for you)
3. Open the options, scroll to the bottom and click "Find Feature"
4. go back to the tab from step 2 and refresh the page
5. click "yes" whenever some PR is dimmed and "no" if all PRs are black/white

### Example URL

https://github.com/xmldom/xmldom/issues

**Comment by cheap-glitch** [comment]
Thanks for the detailed report!

However I tried to reproduce it in the same conditions as mentioned, and I got the correct answer of `dim-visited-conversations`.

My guess is that you must have clicked the wrong button during one of the steps — probably because the color of the visited links isn't very different from the regular one.

**Comment by karfau** [comment]
![screen-recording](https://user-images.githubusercontent.com/135657/155998190-9e9baa4a-015a-4029-b61c-c82c88dbada4.gif)

Just reproduced it again, this time with a recording. If there is more information I should provide, please let me know.

**Comment by cheap-glitch** [comment]
> Just reproduced it again, this time with a recording.

Thank you for the recording! I think I understand where the issue is coming from: on the fourth step (with 6 steps remaining), you clicked "Yes" where it should have been "No", because you saw the collapsed issue at the bottom of the page.

This is not caused by `dim-visited-conversations`, but `dim-bots` instead, which collapses and dims every PR, issue and commit made by a bot. And the "Find feature" mechanism only works properly if focusing on the effects of a single feature.

Your point is valid nonetheless, because the feature finder always starts with every feature enabled, regardless of the user's settings. Since the user might be exposed to features they aren't used to seeing, this can cause confusion and derail the process.

So I think we should make the finder work with only the features already enabled. Not only would it be more straightforward, it'd be faster too (less features to consider = less steps).

**Comment by karfau** [comment]
Thx for the elaboration, i guess the biggest surprise for me is, that the feature finder enables all features.

Maybe it would also be possible to list all possible features that where clicked "yes" for. I guess it would still help to narrow down the problem. Just in case this is simpler to implement.

Of course I agree that only checking the enabled features makes most sense.

Looking forward to it.
Anyways, it's already a really cool feature and I was able to find it when I needed it. So kudos for that.

**Comment by fregante** [comment]
I think it might make sense to start only with the currently-enabled features simply because the user is likely to be looking for a specific feature that they're already seeing. Skipping already-disabled features will also reduce the number of steps.

The only drawback is that the user won't be able to ever find disabled features unless they re-enable them first, but I think that's unlikely (and if they disabled few features it won't be difficult to do that anyway)

**Comment by karfau** [comment]
I have an idea for both cases:
You could let the user pick as the first step if all features should be enabled before starting the search.

I have not contributed to anything in this repo yet. And resource wise I cant promise anything. 
Any hint where to start looking would be helpful for me to judge if I feel capable to pull that off.

**Comment by cheap-glitch** [comment]
> I have an idea for both cases: You could let the user pick as the first step if all features should be enabled before starting the search.

Why not, but I'm not sure there's really a use case for it.

> Any hint where to start looking would be helpful for me to judge if I feel capable to pull that off.

The main logic is in https://github.com/refined-github/refined-github/blob/main/source/helpers/bisect.tsx. It's relatively self-contained, although this change would require an understanding of the way options are stored (which isn't very complex).

**Comment by karfau** [comment]
I did have a look at that code in the browser for half an hour, but I still didn't figure out how it manages to "loop" through the different bisected features.
I will try again using my IDE at some point in time, but so far I don't feel capable of touching that code.

**Comment by cheap-glitch** [comment]
> how it manages to "loop" through the different bisected features

Basically: the list of remaining features is loaded from the cache, split in half according to the user's answer, put back in the cache, and the page is reloaded. Rinse and repeat.

> but so far I don't feel capable of touching that code

That's totally fine! Don't feel obligated to send a PR because you opened this issue.
