### ISSUE TITLE
I would like to have download feature on github even if not Signed in Github

### ISSUE THREAD

**Issue by NSP-0123456** [refined-github/refined-github#5444]
### Description

Feature are not available if not connected to github and no user friendly warning to show that it is not enabled unless you go to the extension option to see errors. 
Some of them like download file/folder should be available even if not connected.

### Example URL

https://github.com/refined-github/refined-github/tree/main/distribution

**Comment by yakov116** [comment]
What do you mean by "not connected"

**Comment by NSP-0123456** [comment]
not signed into github.

**Comment by yakov116** [comment]
Refined Github is intended to work when logged in. If you are not logged in, your on your own.

**Comment by NSP-0123456** [comment]
This exactly the purpose of the suggestion :)
Have refined github  feature (download individual file/folder) even if not signed in GitHub nor ApiKey (Which need to be signed to get one)...
Currently the only way is to use the svn export or GitZip or .... which is not as convenient as the download "buton".

**Comment by fregante** [comment]
Thanks for the request, but:

- You can use the downloader directly, sometimes **without a token**, by visiting https://download-directory.github.io/
- The downloader sometimes requires a token to download some repos, this is just a GitHub limitations, not ours
- As @yakov116 said, Refined GitHub is for GitHub users so we only really support logged-in users

For this reason I'll close this issue.

However it seems that this specific feature should work because the element it's looking for appears to exist:

<img width="223" alt="Screen Shot 9" src="https://user-images.githubusercontent.com/1402241/156340783-3e015d98-2f9c-4df3-8b69-de90ed1c1ead.png">

<img width="485" alt="Screen Shot 10" src="https://user-images.githubusercontent.com/1402241/156340769-3d20001c-9c43-4c2d-a69f-7876a7a3cbbb.png">

but I'm seeing this error:

```
null is not an object (evaluating 'searchButton.nextElementSibling.querySelector')
```

so if anyone wants to fix it, it's a welcome change. Also the tooltip should be shown on the left because it's currently causing an overflow on small viewports.
