### ISSUE TITLE
`wait-for-checks` feature hangs forever if the PR doesn't have any checks at all (but `main` does)

### ISSUE THREAD

**Issue by cuichenli** [refined-github/refined-github#5449]
### What I don't like

I have one repository that only runs certain CI job on the master branch, so whenever I opened a new PR, there will be no commit status for those commits. However, if I clicked the `Merge` button, I would see the checkbox `wait for builds`, which does not make sense. The checkbox got displayed because it detected one CI commit status icon, which is the one near the repository name (the CI I made for master branch only). And if the checkbox is enabled, the merge will never finish, as the `wait-for-builds` feature will wait forever. 

The source code caused this is https://github.com/refined-github/refined-github/blob/main/source/features/wait-for-checks.tsx#L43

<img width="394" alt="image" src="https://user-images.githubusercontent.com/29245119/156510081-25dc0b4c-8235-4703-abe1-cbbdf1d1cfb0.png">

**Comment by fregante** [comment]
This is caused by a recent reliability update in https://github.com/refined-github/refined-github/pull/5393

The issue was that GitHub does not immediately show the CI icon next to each commit (and sometime it forgets to update the UI altogether) so we use "any CI icons on the page" to determine whether the feature should expect some checks to start and finish.

I suppose that we can add more logic to this, for example:

- look for "any CI icons on the commit list" if the commit list was pushed multiple times
- if there's only one push, include `ci-link` in this logic
- add a timeout somewhere, like "if there's no check starting within 10 seconds, then merge"

cc @cheap-glitch

**Comment by fregante** [comment]
The feature needs to be rewritten from scratch because we cannot rely on GitHub’s DOM for this information.

See https://github.com/refined-github/refined-github/pull/5465#issuecomment-1070337400
