### ISSUE TITLE
Pull Request File Tree and `highlight-deleted-and-added-files-in-diffs`

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5461]
### Description

_[A wild Feature preview](https://github.com/github/feedback/discussions/12341) appears!_

<img width="857" alt="image" src="https://user-images.githubusercontent.com/44045911/156830494-f20644d5-0d68-473f-bfa9-1c03aee00be3.png">

It looks promising but now we have some awkward situation with `highlight-deleted-and-added-files-in-diffs`:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/44045911/156830553-3454c723-e2d4-4ddb-988b-9a5483e93da3.png">

- Does it make our feature redundant, since the file tree also shows file status icon?
- If not, do we want to add yellow "Modified" icon just like GitHub?
- Or do nothing?

### Example URL

https://github.com//nice-registry/all-the-package-repos/pull/41/files

**Comment by fregante** [comment]
> * Does it make our feature redundant, since the file tree also shows file status icon?

I'd say no:

- our feature doesn't require opening the sidebar (which I haven't particularly found useful yet)
- our icon appears exactly above the current file so you don't have to go find the current file in the sidebar



> * If not, do we want to add yellow "Modified" icon just like GitHub?

Maybe, but it looks quite redundant. It makes sense for them because they show a list of file just like in the old "jump to file" dropdown. Basically this is not a new feature

<img width="457" alt="Screen Shot 17" src="https://user-images.githubusercontent.com/1402241/156872822-7bc670ed-abcb-448d-9da9-f6b260ab5103.png">
