### ISSUE TITLE
Mark "your recent visit" on conversation lists when sorted by last updated

### ISSUE THREAD

**Issue by Milo123459** [refined-github/refined-github#5475]
### Description

It would be nice if once you have visited an issue/pull request, whenever a new message is sent it un-dims or shows a little marker.

### Example URL

https://github.com/rust-lang/rust/pulls

**Comment by fregante** [comment]
Link dimming is a native browser behavior, plus we can't know when a new message is received unless we fetch and store every single issue you visit. 

Notifications already offer this feature though, the item will have a blue bar when a notification was received.

**Comment by fregante** [comment]
A marker would be better. 

When we implemented the "sort by last update" feature we mentioned the possibility of keeping track of "what's changed since your last visit in the list views. I think this would be more efficient, it would consider any changes across the repo and it would be a single stored date per repo, maybe. 

I'm hesitant to add many more cache items however; our cache still does not automatically clear when full and it silently breaks the options page at that point.

**Comment by Milo123459** [comment]
> A marker would be better.

Would you mind making a mockup?

**Comment by Milo123459** [comment]
<img width="374" alt="ebM4Mx67" src="https://user-images.githubusercontent.com/50248166/157732392-cdc85723-1b88-48ef-b232-2320b70f8f56.png">
Something like this?

**Comment by fregante** [comment]
<img width="1231" alt="Screen Shot 6" src="https://user-images.githubusercontent.com/1402241/157821085-37d13f9b-2929-489d-8e65-4690298c2fa4.png">
<img width="1233" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/157821109-8d708e12-af76-480f-9dda-27b25908e488.png">

**Comment by kidonng** [comment]
I maybe wrong but this is essentially https://github.com/refined-github/refined-github/pull/5258#issuecomment-1003744491.

**Comment by fregante** [comment]
_expired_
