### ISSUE TITLE
Make `toggle-files-button` more noticeable

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5524]
### Description

- Re: https://github.com/refined-github/refined-github/issues/4402

People might collapse the list and forget it. We could improve this:

<img width="921" alt="Screen Shot 9" src="https://user-images.githubusercontent.com/1402241/159109668-b494da0c-54e9-489c-86f5-1092c283714f.png">
 

to this:

<img width="923" alt="Screen Shot 10" src="https://user-images.githubusercontent.com/1402241/159109670-a03d2e89-f173-4e5b-846f-ed4486186dea.png">

### Example URL

https://github.com/refined-github/refined-github

**Comment by cheap-glitch** [comment]
I'm kinda -1/+1 on this, it's not a big deal but I like the clean look of the collapsed file list.

That said I agree we need to make it more obvious, since we've had at least a couple of confused users reporting this as a bug. How about:

1. Making the collapse/uncollapse icon more prominent
2. And/or showing a notice like in your mockup, but only when hovering the file list header

**Comment by fregante** [comment]
1. I don’t think there's any change we can make that fits both GitHub's style *and* would actually make it visible enough (the eyes go to where the list should be, and the button isn't there, it'd have to fight quite a bit to catch the attention)
2. Changing layout on hover is challenging, see dim-bots and its delays. Plus users don't necessarily hover the line, they'll just expect the list to be there and be frustrated if it isn't
