### ISSUE TITLE
"All" mode for "one-click merge conflict fixers" (`resolve-conflicts`)

### ISSUE THREAD

**Issue by janpio** [refined-github/refined-github#5615]
### Description

The added buttons/links to resolve conflicts are super useful:
![image](https://user-images.githubusercontent.com/183673/166008783-b3021e99-81d1-408d-9479-7fc1db78848a.png)

For some types of conflicts (e.g. package.json and .lock updates to `main` in our case) you might know that you will want to `Accept incoming change` for all of them. It would be amazing if there was a way to resolve all merge conflicts in a specific way (Incoming Change, or Current Change) either a) for the complete PR or b) for each of the conflicted files. The button could sit at the top where the "Merge" button appears for a), and next to "Mark as resolved" for b). 

(If I had to choose between the options a) and b), I would prefer a) as that is my actual workflow.)

### Example URL

https://github.com/prisma/prisma/pull/13083/conflicts

**Comment by fregante** [comment]
I don’t think it's feasible to accept all changes across files: it'd have to slowly load each file sequentially. We can however act on all changes on the same page.

If you're willing to implement this, it can be implemented without additional UI, by just detecting alt-clicks on each of those choices. We do this in many other features, with the exception that here we'd act directly on the file (e.g. "search and replace **all**") instead of automatically "clicking the widget" multiple times.

**Comment by fregante** [comment]
Too many feature requests, realistically we’ll never get there. I’m closing those I think aren’t worth it.

**Comment by janpio** [comment]
So sad. This would be so useful for the few times I need to use this and click a thousand times.

But I understand.
