### ISSUE TITLE
Automatically enable GitHub Actions workflow(s) for forked repositores

### ISSUE THREAD

**Issue by Margen67** [refined-github/refined-github#5629]
### Description

Having to manually enable GitHub Actions workflows is an annoyance. Sometimes I forget to enable them before pushing commits.

### Screenshot

![Something like this](https://user-images.githubusercontent.com/16872793/92803886-dc460e00-f385-11ea-8af6-d6b7a0d3bf91.png)

### Example URL

https://github.com/refined-github/refined-github/fork

**Comment by fregante** [comment]
I think in generally one doesn't need to use CI on the fork because it may depend on secrets. This could be useful for simple CI tests that can run on the fork before they are approved in the PR on the upstream repo, but in reality these results might not be visible in that workflow. 

So in practice it'd end up wasting CI or confusing users with failing CIs that are failing only due to missing secrets.
