### ISSUE TITLE
Recently Used Labels/Milestones/Assignees

### ISSUE THREAD

**Issue by hediet** [refined-github/refined-github#5671]
### Description

For maintaining VS Code, we intensively use labels to classify issues as bug/feature-request/etc. and to mark their feature-area, so that finding duplicates is much easier.

We also use assignees and milestones a lot.

It would be awesome to have some "Recently Used" feature to allow one-click selections of recently used labels (see the screenshot for clarification).

Currently, assigning a label takes many steps.

I'm open to help implementing this feature, but I struggled to programmatically modify which labels are selected.

I'm also willing to sponsor the development of this feature.

### Screenshot

![image](https://user-images.githubusercontent.com/2931520/171623338-8c8cc4b4-5b6d-40b4-8fbc-81b64ae5dd3d.png)

### Example URL

https://github.com/microsoft/vscode/issues/151041

**Comment by fregante** [comment]
It's unlikely that we'd add those outside the picker because that'd basically break our "sticky sidebar" feature and be potentially confusing because that's not particularly visually different from labels that are _already_ attached.

The feature would make sense as part of each picker itself, where the user already expects to pick labels (etc), this would only add one click but it would solve every UI/UX issue (and also simplify the code to actually add the label, because GitHub would handle that)

The frequently-used labels would appear at the top of each respective list so that you don't have to search for them. 

This is probably still a relatively-complex feature but maybe we can get away with just:

- remembering the last label (we can use our existing caching mechanism to save the date)
- moving the existing dom elements to the top of each list when the user opens the dropdown/picker

**Comment by hediet** [comment]
That makes sense! However, when the label picker is opened, you need to close it to accept the change (if you close the tab without closing the picker, the label is not added). This means that what you describes requires three clicks instead of one per category.

It would still be a huge improvement, as right now, I need to type the name of the label every time. Just went through ~20 issues today already...

**Comment by fregante** [comment]
I'd love this at least for labels. GitHub already has a visually-similar situation that we should replicate and/or extend:

<img width="333" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/171993743-84f0567e-7888-4008-8a72-7e5facd1a495.png">

The filter seems to keep working even after changing the DOM, so this feature should:

1. Wait for the dropdown to open and load
2. select any labels that were recently used for this repo
3. use `list.prepend(<SuggestionsHeader/>, ...labels, <OtherLabelsHeader/>)`

> any labels that were recently used for this repo

Alternatively, maybe we should just track the 10 most common labels across repos and just display 3/4 per repo. We need to track more than we display in this case because if the most common are `bug, enhancement, help wanted`, a second repo with `type:bug` will never have a chance to appear.



> * remembering the last label (we can use our existing caching mechanism to save the date)

On second thought, can't do that because we'd have to query the entire storage to find them. It's best to store a single object like:

```js
{
	bug: [10, lastUseDate],
	enhancement: [8, lastUseDate],
	"help wanted": [2, lastUseDate],
}
```

**Comment by hediet** [comment]
> On second thought, can't do that because we'd have to query the entire storage to find them. It's best to store a single object like:

I also prefer the recently-used approach (tracked per developer or browser profile), as this adapts much better to dynamic situations (e.g. when this month you get lots of issues in this area and next month in another area).

> I'd love this at least for labels. 

It still would be very nice to have this for milestones too.
And I still think a one-click solution might be really valuable.

Here is another idea for a milestone shortcut:

![image](https://user-images.githubusercontent.com/2931520/172046166-8ba30b7e-fcd1-4604-ad6e-8de7bb606998.png)

When a milestone is selected:

![image](https://user-images.githubusercontent.com/2931520/172046187-e2495370-7581-4d02-8e7c-f2aa8b1331c7.png)

**Comment by fregante** [comment]
As mentioned, the one-click solution makes the sidebar really busy and confusing. That layout wouldn't work for long labels or any more than 2 items. 

On top of that, pulling those out would make the feature considerably more difficult because we'd have to handle the display (including remembering/fetching the label colors) and the API calls to save each addition, instead of relying on the native widget. It would be too much as part of Refined GitHub. 

As I describe it, it would probably already be one of the longest features.

**Comment by hediet** [comment]
Maybe it actually is not so hard to implement at least the milestone-on-click feature as a separate user-script.

This works to trigger the milestone form:
```ts
$("[data-menu-trigger=milestone-select-menu]").click()
```

And this can be used to select a milestone by name:
```ts
$$("[data-filterable-for=context-milestone-filter-field] .select-menu-item .select-menu-item-heading").filter(x => x.innerText === "June 2022")[0].parentElement.click()
```

Maybe that script could also intercept whenever the form closes to figure out which Milestone was selected last.

**Comment by fregante** [comment]
I'd love to see it, but I don't see it happening here due to the complexity. If anyone is willing to sponsor its development (~$1k) I can reconsider it.

**Comment by fregante** [comment]
Implemented by GitHub, at least for labels:

<img width="333" height="440" alt="Image" src="https://github.com/user-attachments/assets/f19ff0c5-f7fb-4726-90ff-e7292e0ee5a0" />
