### ISSUE TITLE
Disable search in text editor

### ISSUE THREAD

**Issue by gcbw** [refined-github/refined-github#5688]
### Description

Prevent the custom javascript search when editing a file from the UI, and use the native browser search.

If this have to disable everything they add to their custom textarea (soft line wrap, line numbers, etc), so be it. Then we could just call "use native textarea for file edit" instead of "disable custom search".

I rarely edit files on the github UI, but when I do I immediately regret it as soon as I press Ctrl+F. It is awful in every aspect.

### Example URLs

https://github.com/org/repo/edit/main/file

**Comment by fregante** [comment]
That isn't possible because CodeMirror (the editor you see) doesn't render the entire file on screen. The lines that are not visible, are not part of the dom at all, so the browser cannot find it.

You have two solutions:

- break CodeMirror so it leaves a raw `textarea` (not very practical)
- use GhostText: https://ghosttext.fregante.com

Other than this, Refined GitHub unfortunately can't do anything about it, as much as I also don't like the custom search.

**Comment by gcbw** [comment]
Thanks for the background on this! much appreciated.

would blocking codeMirror be a feature here?

**Comment by amacfie** [comment]
> Thanks for the background on this! much appreciated.
> 
> would blocking codeMirror be a feature here? ~I tried to block it via my adblocker, but there's no individual network request i can use to block it :(~ Here is the "fix" via [uBlock origin](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#modifier-filters): `||*/assets/editor-$script,domain=github.com` (just update the domain at the end for corporate urls)
> 
> ...Will try ghosttext and report back, but i'm almost sure it will not help until we get the raw text area to begin with.... Update: correct, it won't work until after you blocked the editor script. After you blocked, it is the best.

At the moment the rule `https://github.githubassets.com/assets/react-code-view-*.js` seems to work
