### ISSUE TITLE
`submission-via-ctrl-enter-everywhere` errors on Releases page

### ISSUE THREAD

**Issue by cheap-glitch** [refined-github/refined-github#5725]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/refined-github/releases

### Extension version

Latest `main` build

### Browser(s) used

Firefox

### Description

```
addQuickSubmit@moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/refined-github.js:14750:57
runFeature@moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/refined-github.js:8479:22
setupPageLoad@moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/refined-github.js:8491:11
./features/index.tsx/add/<@moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/refined-github.js:8555:14
dispatchTurboEvent@moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/refined-github.js:18215:12
```

### Include in this issue:

- [ ] Screenshots/video/gif demonstrating the bug, if it’s visual
- [X] Console errors, if any

**Comment by fregante** [comment]
Related: we should enable the feature on release edit pages

**Comment by fregante** [comment]
- Bug fixed by https://github.com/refined-github/refined-github/pull/5727/files#diff-761e43d505e7006dc33f66bf8b56efc312b1fe809dabe634471c5695ea88df64
- Regarding my comment, I remember it not working when editing releases, but the feature always had `isEditingRelease` and it seems to work now. Will open a new issue if I still see it
