### ISSUE TITLE
RGH breaks highlighting of current repo tab

### ISSUE THREAD

**Issue by cheap-glitch** [refined-github/refined-github#5758]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.
- [X] The bug happens after clearing extension cache. The "Clear cache" button below can also be found at the bottom of the options page.

### Example URLs

https://github.com/refined-github/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

### Extension version

Latest `main` build

### Browser(s) used

Firefox

### Description

https://user-images.githubusercontent.com/46634000/176734731-d26b5cb6-4a9b-4eee-b166-67024e6bce25.mp4

1. Go to https://github.com/refined-github/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc & reload the page
2. Go to "Code" or "Issues" tab
3. "Pull requests" is still highlighted

This doesn't happen every time though, so there might be some kind of race condition that conflicts with the native highlighting.

### Include in this issue:

- [X] Screenshots/video/gif demonstrating the bug, if it’s visual
- [ ] Console errors, if any

**Comment by kidonng** [comment]
Haven't seen this once, assume fixed.

**Comment by cheap-glitch** [comment]
I still see it in Firefox with the latest version of RGH.

**Comment by kidonng** [comment]
Oops, sorry! Just tested it is indeed the case.

**Comment by fregante** [comment]
Tentatively closing because I think this is due to:

- https://github.com/refined-github/refined-github/issues/5821

Reopen if you can confirm that it happens without going across repositories (just look at the "back button" history by clicking and holding the back button)

<img width="600" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/183140461-06aada8b-6313-47eb-9bfc-173ad51126bc.png">
