### ISSUE TITLE
`comment-on-draft-pr-indicator` broken on pull request files

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5815]
### Description

On PR conversations it works fine.

### How to replicate the issue

1. Open https://github.com//refined-github/refined-github/pull/5807/files
2. Click any line to bring up comment popup
3. Notice comment button texts aren't changed

### Extension version

22.7.11

### Browser(s) used

Chrome

---

Honestly I think this feature is biased. Reading #3857 I feel it is solving a very specific need. Why doesn't it also tell you are commenting on a closed PR? Or merged PRs? Or ancient (say, > 1000 days) PRs?

**Comment by fregante** [comment]
Regarding ancient PRs: we could add a banner near the comment box on issues that says “this issue was closed 2 years ago”


Alternatively, yes, I wouldn’t mind adding a warning icon right next to the button:

- ⚠️ Draft [Comment]
- ⚠️ Old [Comment]

With tooltip on the ⚠️ or ℹ️ that explains the warning better.
