### ISSUE TITLE
`jump-to-conversation-close-event` error on pull request commits

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#5818]
### Description

Error on `isPRCommit`:

```
refined-github.js:8642 Uncaught TypeError: Cannot read properties of undefined (reading 'closest')
    at addToConversation (refined-github.js:8642:200)
    at runAdd (refined-github.js:22353:20)
    at applyChanges (refined-github.js:22269:7)
    at SelectorObserver.addRootNodes (refined-github.js:22789:3)
    at Array.processBatchQueue (refined-github.js:22210:5)
    at MutationObserver.handleMutations (refined-github.js:22244:19)
```

### How to replicate the issue

1. Open [`7e8bb26` (#2182)](https://github.com//refined-github/refined-github/pull/2182/commits/7e8bb264cda190a5ce2e09e51196cb8f4b230696)
2. See error

### Extension version

22.7.11

### Browser(s) used

Chrome

**Comment by yakov116** [comment]
This is really a (my) mistake in https://github.com/refined-github/github-url-detection/.

I should have made 2 detections. One for closed conversations (only the conversation) and one for a PR thats closed.

**Comment by yakov116** [comment]
Unless maybe we should just include `isConversation`?

**Comment by fregante** [comment]
The error comes from our ambiguous usage of “conversation”. We have “isConversationList” to describe “is list of issues and PRs” but “isConversation” describes “is issue or specifically then conversation tab or a PR”

So “isClosedConversation” makes sense using the first meaning but not the second one. 

Let’s add an additional “isConversation” to the feature’s “asLongAs”, simply because that’s how the nearby detections are used (isOpenPR, etc). I’m afraid that if we change the detection we’ll end up wanting the opposite in the future. 

Related: 

- https://github.com/refined-github/refined-github/issues/5389
