### ISSUE TITLE
User CSS is removed after navigation 

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5857]
### Description

Mentioned in https://github.com/refined-github/refined-github/issues/5719#issuecomment-1195635868

Something similar was fixed in https://github.com/refined-github/refined-github/pull/5752

This doesn't happen with every type of navigation, but only some, like when opening a new issue:

![before](https://user-images.githubusercontent.com/1402241/181179438-a0508437-563e-427c-a722-11a50303378f.gif)

### How to replicate the issue

1. Add `* {background: red}` to the CSS
2. Open https://github.com/refined-github/refined-github/issues in a new tab
3. Notice red background
4. Visit any issues
5. See white background 

### Extension version

22.7.1

### Browser(s) used

Safari

**Comment by kidonng** [comment]
LOL I saw https://github.com/refined-github/refined-github/issues/5719#issuecomment-1195635868 2 hours ago, but didn't immediately reply and went to do something else.

I even just got my screen recording ready!

<img width="142" alt="image" src="https://user-images.githubusercontent.com/44045911/181180753-13013dd2-bceb-45d8-a8cb-460245d83575.png">

Anyway here's it, as you can see it also happens when I open a repository from another repository (User CSS from [here](https://github.com//refined-github/refined-github/pull/3356#issuecomment-660019295))

https://user-images.githubusercontent.com/44045911/181180999-6484cf8f-9714-49a6-b0de-b97128f6ad6b.mov

**Comment by ian-h-chamberlain** [comment]
Worth noting, I am seeing this on Firefox 102.0.1 so it seems to be browser-independent behavior.

**Comment by fregante** [comment]
It turns out this is what I was (and still am) experiencing in https://github.com/refined-github/refined-github/issues/5222#issuecomment-1179648629

**Comment by fregante** [comment]
Quick fix: 

1. revert https://github.com/refined-github/refined-github/pull/5493
2. reopen https://github.com/refined-github/refined-github/issues/4731#issuecomment-1066059907
