### ISSUE TITLE
Restore plain paste

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5900]
### Description

Context:

- https://github.blog/changelog/2021-11-10-linkify-selected-text-on-url-paste/

This feature was [suggested in RG](https://github.com/refined-github/refined-github/issues/4310) and I was against it because it was troublesome.

Months after it's been added, I still struggle with every paste.

Want to copy-paste a username to mention someone? Wrong. You'll get a markdown link

<img width="375" alt="Screen Shot 11" src="https://user-images.githubusercontent.com/1402241/183234917-d1b47e69-9089-4bb2-9c2f-e868a5ea54bf.png">

Want to select a chunk of text and replace it just like it happens everywhere else on your computer? Wrong. If you're pasting a link, now you just wrapped the whole piece of text in a link instead.

<img width="630" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/183234874-37f3f0ee-4973-4bb1-a985-e5fe45fbee20.png">

### Solution

I think this feature would need to listen to pastes like GitHub does and:

- if there's a plain link or "rich text", we should insert it via `textFieldEdit.insert` and then `preventDefault` I think

### Example URLs

This page.

**Comment by kidonng** [comment]
The linked blog post isn't the one announcing what is being described here. It's this update: https://github.blog/changelog/2022-05-19-updates-to-markdown-pasting-on-github/

The title of this issue should be "Restore plain paste **by default**", because pasting as plain text is available (via shortcuts like in rich text editors), mentioned in the second blog post.

Previously, the linkifying only happens when:

- The clipboard has a plain link [1]
- The selected text is not (in) a markdown link [2]

The second update expanded [1] to any rich text with link, and [changed the behavior of [2]](https://github.com/community/community/discussions/18422).

[1] is not a bug per se, it's GitHub made comment fields behave more like a rich text editor, via pasting markdown link (the closest thing available to actual rich text) by default.

For [2], while it looks like a bug since it used to work, I guess they just stopped doing these work and suggest pasting as plain text. I tested with [the most popular Markdown extension for VSCode](https://github.com/yzhang-gh/vscode-markdown) and it doesn't handle those two cases linked above either.

**Comment by fregante** [comment]
You're just being pedantic now. None of that matters, what matters is whether GitHub’s behavior is welcome, on which you agree:

> This is unwelcoming

**Comment by kidonng** [comment]
Is providing more context also unwelcoming? I also just realized pasting as plain text does exist after seeing this issue and investigating.

Fighting a GitHub default like this is not trivial and I want more consideration. I certainly don't like the current default, but I do love the previous one, so there is a need to describe more thoroughly.

**Comment by FloEdelmann** [comment]
Plain text paste can now be enabled in the user accessibility settings: https://github.com/settings/accessibility

Announcement: https://github.blog/changelog/2022-09-27-the-new-github-issues-september-27th-update/#%F0%9F%96%8C--paste-urls-formatted-or-as-plain-text

**Comment by FloEdelmann** [comment]
Personally, I'd actually like a third option there: When pasting a URL while having text selected, format to a Markdown link, like GitHub currently does by default. But when copying rich-text, ignore all formatting including links and paste as plain text.

**Comment by fregante** [comment]
Ahhh love that. Thank you for the report

 Keeping the formatting is ok until you try to copy-paste a username (as shown in my gif)
