### ISSUE TITLE
Context menu in GitHub with refined-github

### ISSUE THREAD

**Issue by codehangen** [refined-github/refined-github#5935]
Hi!  I would like to have a context menu so that I can easily rename [.txt .md ...etc] files without having to go inside folders to make commits.  Software like Ghost Writer, Adobe Photoshop, Gimp have a context menu to facilitate certain actions with the mouse. Currently, GitHub does not have this feature natively in the web interface.  

Some developers have requested this feature on GitHub Discussions, but there has been no official response regarding this feature.  Since the extension/userscript is intended to bring small refinements to GitHub, I thought it would be interesting to discuss whether this is possible in this project. 

With this feature it would be possible to have a context menu on GitHub for mouse actions such as moving files, renaming folders, deleting files and folders and this could improve GitHub as well as bring the necessary refinements to this. I would be happy with any positive or negative feedback on this question.

**Comment by fregante** [comment]
I have a few issues with this:

- the actions you're describing are probably already available via keyboard shortcut, so a context menu would not be any faster
- GitHub very much looks like a website rather than an app and generally people don't use the context menu to take actions on websites
- implementing context menu items in extensions is kinda annoying because the event happens in the background page, which then has to synchronize with the current page. Even just registering them as a "feature" would mean having to write a good chunk of code to handle enabled-disabled features. Refined GitHub runs almost exclusively on the main page


The last part leads me to say no to this. I'm sure it can be part of its own extension though.

**Comment by yasinnaal** [comment]
Github rename subfolder...
