### ISSUE TITLE
GitHub’s content refresher partially undoes `shorten-links`

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#5963]
### Description

Somehow, GitHub is undoing `shorten-links`. This is somewhat related to #5870.

You can see here that some links weren't shortened, until I caused the PR to update (by mentioning it in another thread) and it finally reapplied (slow video, wait)

I have no idea how this could evade the new selector observer 🤷‍♂️ 

https://user-images.githubusercontent.com/1402241/189528075-05dcaaaf-c64f-453c-af22-f8404d944353.mov

### How to replicate the issue

1. Visit https://github.com/refined-github/refined-github/pull/473

Maybe you'll find the same situation

### Extension version

22.9.9

### Browser(s) used

Chrome, Safari

**Comment by fregante** [comment]
Help here is welcome for finding out what's happening exactly.

**Comment by chcamiloam** [comment]
Hi, I think the problem is related to the library in charge of making the URL shorter,
In the image looks like the process is working and it is removing some things of the URL, but with the URLs with params, it only remove the params, and doesn't change all the URL, I can check the library if you want.

Also I was checking why it worked when you update the PR, and looks like we are "shortening" the url shorted before, and the library affect the URL with params twice or a different validation is applied.

<img width="746" alt="image" src="https://user-images.githubusercontent.com/26499470/189605905-1feac705-8bcb-413e-8c0c-c6c4af26d812.png">

**Comment by fregante** [comment]
Duplicate of https://github.com/refined-github/refined-github/issues/5890
