### ISSUE TITLE
Add a `Hide all commits` option to `conversation-activity-filter`

### ISSUE THREAD

**Issue by justinchuby** [refined-github/refined-github#6047]
### Description

The ability to filter conversation activities is great. It would be nice to extend it to filter out / hide commit activities, as pull requests that are frequently updated can leave a big trace of commit activities that make the conversation hard to read.

### Screenshot

These commits can be hidden

<img width="734" alt="image" src="https://user-images.githubusercontent.com/11205048/194443116-a3bc8eec-d012-42e8-b4f7-c26f743ac116.png">

Ideally it can be set via this dropdown and/or set as default somewhere in settings.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/11205048/194443166-b66a1682-4bd3-4819-971f-22ad2fed0d6d.png">

### Example URLs

https://github.com/pytorch/pytorch/pull/85312

**Comment by fregante** [comment]
We used to hide them, but reverted the change:

- https://github.com/refined-github/refined-github/issues/5581
- https://github.com/refined-github/refined-github/pull/5582

The feature has a lot of potential for _options_ and I'd rather keep it simple in order to cycle through the options easily.

Related:

- https://github.com/refined-github/refined-github/issues/5929

**Comment by justinchuby** [comment]
I wonder if it's possible to analyze the history and selectively hide commits that are caused by force pushes. Looks like it will be more useful only for repos that uses force pushes and rebasing in development.

**Comment by fregante** [comment]
While it kind of makes sense, I'm going to close this because:

- commits are a fundamental part of reviews, which is what this feature specifically attempts to help

and:

> The feature has a lot of potential for _options_ and I'd rather keep it simple
