### ISSUE TITLE
Keyboard shortcut to approve PR review

### ISSUE THREAD

**Issue by tonglil** [refined-github/refined-github#6097]
### Description

Use the unused `cmd+shift+enter` keyboard shortcut to "approve" a PR review.

- `cmd+enter`: comment
- `cmd+shift+enter`: approve

Following up from https://github.com/refined-github/refined-github/issues/5010.

There are no userscripts for this.

### Example URLs

https://github.com/refined-github/refined-github/pull/6095/files

**Comment by ian-h-chamberlain** [comment]
A shortcut for `Request Changes` might be nice too, although picking a shortcut for that case is probably tricky since you'd want to avoid accidentally pressing it (same for approving, I guess).

This isn't exactly helpful for the case where you're already writing a comment, but I've also  wanted a shortcut I can use without focusing the comment box at all, to quickly review a PR without adding additional commentary, for example:
* `v` `a` – approve without comment
* `v` `r` – request changes without comment (more rare, but maybe nice to have for symmetry)

**Comment by fregante** [comment]
PR welcome.

- The shortcut should be added to the button itself via data-hotkey (or the variant that limits the shortcut to the containing form, so it's not a global shortcut) 
- The button should mention the shortcut in the tooltip, I think. I'm not a fan of shortcuts that nobody knows about (and that I myself don't remember)

**Comment by fregante** [comment]
- Cmd+Enter already sends a comment, natively
- Approval is best left to do without keyboard shortcuts
