### ISSUE TITLE
Improve status-aware favicon: consider mergeability

### ISSUE THREAD

**Issue by dabrady** [refined-github/refined-github#6134]
### Description

Aloha!

In #368, we were discussing the wonderful idea of having the favicon of pull requests change according to its status. Before we got around to implementing a solution, GitHub gave us theirs.

However, as mentioned in [the last comment](https://github.com/refined-github/refined-github/issues/368#issuecomment-391621365) on that closed issue, the status-aware favicon only seems to consider CI checks, and does not reflect the overall 'mergeability' of the pull request. For example, if the CI checks pass but the PR has not been approved and a review is required, the favicon shows the "good to go" status instead of the "merging is blocked" status.

It would be wonderful if we could improve the behavior native GitHub provides, to give a more meaningful status indicator.

### Screenshot

In this example, the PR is not mergeable because it has not been approved:

<img width="660" alt="image" src="https://user-images.githubusercontent.com/2475919/199812494-a2ec858f-a9e4-44f2-8775-4b0789a5def1.png">

In this example, neither PR is mergeable, but the favicon of one of them doesn't reflect that:

<img width="240" alt="image" src="https://user-images.githubusercontent.com/2475919/199813982-afdf6ced-6dae-4782-b59d-58b52703ef54.png">

### Example URLs

(my pull requests are for a private organization, sorry; but my screenshots hopefully tell the story)

Sample from the other issue

![image](https://cloud.githubusercontent.com/assets/9487348/23832966/2a05491c-073f-11e7-98c6-a68e669d9d4c.png)  
![image](https://cloud.githubusercontent.com/assets/9487348/23832967/3438b23e-073f-11e7-9615-3a41ed10e7b7.png)  
![image](https://cloud.githubusercontent.com/assets/9487348/23832969/3989285e-073f-11e7-8471-63e22c69954c.png)

**Comment by fregante** [comment]
I see a few problems:

- since GitHub already touches the icon, we have to actively override it and hope GitHub doesn't immediately change it back, causing a loop
- we can't override the native checkmark and turn it red because people expect the checkmark to mean "CI" now, not "general status," so we need a second checkmark next to it
- including dark mode, there would be 2(dark mode)x2(CI)x2(reviews) separate icons to generate 
- when tabs are in the background, the data on the page isn't very reliable and we can't poll the API for every open tab

I'm not particularly sure I want to fight GitHub's code here *and* produce 8 separate icons for this.
