### ISSUE TITLE
In `bug-tab`, the portion of `supportedLabels` detecting labels with a prefixed bug emoji isn't working in one case

### ISSUE THREAD

**Issue by blakeNaccarato** [refined-github/refined-github#6144]
### Description

In `bug-tab`, the portion of `supportedLabels` detecting labels with a prefixed bug emoji isn't working in one case. This still seems to happen after "Clear cache".

### How to replicate the issue + URL

The offending portion seems to be `(:[\w-]+:|\p{Emoji})bug`, for `bug-tab` label. I noticed it [here](https://github.com/iterative/dvc/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22%3Abug%3A+bug%22), on a bug label that looks like `🐛 bug`. Could it be the whitespace between the `🐛` and `bug`?

Here's the relevant line of code:

https://github.com/refined-github/refined-github/blob/93aedc3a717c85dd17fdbd01d7bf8662073eac19/source/features/bugs-tab.tsx?rgh-link-date=2022-07-06T01%3A27%3A37Z#L15

### Extension version

22.10.26.814

### Browser(s) used

Chrome Version 107.0.5304.88 (Official Build) (64-bit)

**Comment by fregante** [comment]
Thank your the report, PR welcome to fix it.

**Comment by fregante** [comment]
On the linked page there's no longer such label, which seems to be supported due to this line:

https://github.com/refined-github/refined-github/blob/f9366820815cc0305efcb83de66fe1fe999d1a7b/source/features/bugs-tab.tsx#L18

The tests I added in https://github.com/refined-github/refined-github/pull/6754 seems to confirm it. Closing
