### ISSUE TITLE
Full screen config

### ISSUE THREAD

**Issue by 3kh0** [refined-github/refined-github#6156]
### Description

Currently, the extension only has this small UI in a small box on the extensions page, so I think it might be better that when you right click the icon on the toolbar, and click options, it would open a new page this would be hosted on the extension, kinda like uBlock origin

### Screenshot

![2022_11_12_0so_Kleki](https://user-images.githubusercontent.com/58097612/201496572-7bd07383-42dd-46cc-854b-66bd79b0cbbe.png)

### Example URLs

N/A

**Comment by fregante** [comment]
There are a few issues with this, namely that Firefox does not offer a link to the options page in this case (or I missed it)

If you find yourself needing a larger page, you could do what I occasionally do:

1. Right click
2. View source
3. Remove: `view-source:` from URL bar

<img width="618" alt="Screenshot 6" src="https://github.com/refined-github/refined-github/assets/1402241/c79b6e28-4c8c-4254-8230-f95535e61807">

<img width="339" alt="Screenshot" src="https://github.com/refined-github/refined-github/assets/1402241/502579ab-4374-4a58-8a18-046611eef9eb">

We can reconsider this in the future since Safari already does open the options in a new tab
