### ISSUE TITLE
Feature Idea: Include name of last change author

### ISSUE THREAD

**Issue by iduuck** [refined-github/refined-github#6197]
### Description

Hey guys, I currently opened some issues over at [FormidableLabs/groqd](https://github.com/FormidableLabs/groqd), and commented on those.

It would be super kick-ass, if the would be able to add a new "update 10 minutes ago **by @iduuck**" for example. So that I am able to quickly scan the issues, and see, if someone replied after me, or the CI told something about the pull requests, OR even a new reply by someone else just 1 minute after my reply.

With the current view, I need to go into the issue, and have a look, who was the last updater.

### Screenshot

<img width="524" alt="CleanShot 2022-12-13 at 10 34 03@2x" src="https://user-images.githubusercontent.com/325241/207281510-28af1c75-e876-4729-8320-8fe5d264b1ae.png">

### Example URLs

https://github.com/FormidableLabs/groqd/issues

**Comment by fregante** [comment]
We're generally against the idea of adding more pieces of information to the view because, especially for PRs, it's already quite busy. 

I'm not entirely sure this piece of information is available in the API at all, because for example someone might post a comment and delete it, leaving no trace except for changing that timestamp.
