### ISSUE TITLE
Make checkmarks more visible

### ISSUE THREAD

**Issue by Avasam** [refined-github/refined-github#6220]
### Description

Checkmarks (especially disabled ones when you can't edit a post) are really hard to discern between checked and unchecked.
Making them hard to use for tracking steps or a checklist of items to be completed.
Refined GitHub could help by increasing the contrast between the two states.

### Screenshot

![image](https://user-images.githubusercontent.com/1350584/212076432-6ad31515-e64d-43cb-b3e9-a15531527915.png)

### Example URLs

https://github.com/python/typeshed/issues/9006

**Comment by fregante** [comment]
This isn't something we should do because those are handled by your browser/OS. It already works well for many, so if we make changes for you we'll break it for others.

<img width="55" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/212347632-ae8eab6d-d3a2-4873-84fb-85d3161206de.png">


The lucky thing is that we offer a CSS field where you can include a very simple style like:

```css
:checked {
  filter: contrast(2);
}
```
