### ISSUE TITLE
Link to github io only works on `.github.io` repos, but older ones are `.github.com`

### ISSUE THREAD

**Issue by iboB** [refined-github/refined-github#6228]
### Description

GitHub Pages switched the name of the repo from `username.github.com` to `username.github.io` about 8 years ago. As a result [many .com repos are still active](https://github.com/search?q=github.com&type=repositories) even though they actually result it `.github.io` pages. For example https://github.com/resume/resume.github.com leads to https://resume.github.io/

The feature that puts a hyperlink to the associated website only works with the new repo-to-page name and disregards the `.github.com` repos.

### How to replicate the issue + URL

Open any old GitHub Pages repo like: https://github.com/resume/resume.github.com and observe that there is no link

### Extension version

any

### Browser(s) used

any

**Comment by fregante** [comment]
I'm hesitant because:

- it's been 10 years: https://github.blog/2013-04-05-new-github-pages-domain-github-io/
- the .com doesn't work anymore so it doesn't make sense to keep the repository named that way, especially since GitHub will gladly redirect any old links

However I don't see any reason not to point these repos to the .github.io URL. PR welcome
