### ISSUE TITLE
Add keyboard shortcut to `open-all-notifications`

### ISSUE THREAD

**Issue by 0xdevalias** [refined-github/refined-github#6273]
### Description

Currently, when we have multiple notifications 'checked', there is a button in the 'action bar' to open selected notifications in new tabs/window.

When using keyboard shortcuts (default: `j` / `k`, but ideally also arrow keys if #6272 gets implemented; and `x` to select), and I have multiple notifications selected, it feels weird/confusing that the default `o` / `enter` shortcuts only open the single currently selected shortcut.

Ideally I would like for `o` (at the very least) to open all of my selected notifications, in the same way that manually clicking on the 'Open' button in the 'action bar' does. It would be fine if `enter` remained only opening the currently highlighted one.

### Screenshot

![image](https://user-images.githubusercontent.com/753891/215881401-d9d76ae1-d40c-4de3-92ae-ff41ab4bfc8f.png)

![image](https://user-images.githubusercontent.com/753891/215882156-b2bfe630-1037-49f2-91c3-340a6246feac.png)

### Example URLs

https://github.com/notifications

### See Also

My other `/notifications` feature requests:

- https://github.com/refined-github/refined-github/issues/6272
- https://github.com/refined-github/refined-github/issues/6274
- https://github.com/refined-github/refined-github/issues/6275
- https://github.com/refined-github/refined-github/issues/6276

**Comment by fregante** [comment]
I like this one, it makes perfect sense. GitHub can't do it because the browser blocks multiple popups, but we can extend it.


This would be a change in behavior I think though. The "selection" used by this I think is actually "the focused item", not "the checked items(s)". I'm not sure if we should override this behavior. 


However since we already add an Open button to the notifications page (as well as Issue lists) I would not mind adding a custom hotkey for it specifically n

**Comment by 0xdevalias** [comment]
Hacking around in DevTools just now, it seems that just by adding the `data-hotkey='n'` attribute to the `button.rgh-open-selected-button` enables this shortcut.

Haven't looked into the 'official way' of implementing it in `refined-github` though.

**Comment by fregante** [comment]
That's the right away, you can just add the attribute to our element
