### ISSUE TITLE
No `Attch an image or video` icon in issue editor when edit issue

### ISSUE THREAD

**Issue by tjx666** [refined-github/refined-github#6349]
### Description

No `Attch an image or video` icon in issue editor when edit issue

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/219467478-b9e1174d-4764-4c20-bd5f-e6db3e076103.png">

### How to replicate the issue + URL

You can comment this issue and edit it

### Extension version

23.2.11

### Browser(s) used

Chrome 110.0.5481.100

**Comment by fregante** [comment]
Technically not even a bug because that icon is offered by GitHub and hidden by GitHub in some cases.

Additionally, there's still a bar in this case:

<img width="585" alt="219467478-b9e1174d-4764-4c20-bd5f-e6db3e076103" src="https://github.com/refined-github/refined-github/assets/1402241/9ee441a1-3a54-4300-8754-0bb971ccab13">
