### ISSUE TITLE
Releases are hidden entirely on repos that only have pre-releases or tags

### ISSUE THREAD

**Issue by dimitropoulos** [refined-github/refined-github#6403]
### Description

For repos that have pre-releases only, such as `v0.x.x` semver packages, the default settings are such that users of this extension cannot see a releases tab at the top (or on the right sidebar since `clean-repo-sidebar` is on by default).

I can empathize with the desire to hide pre-releases in the case where a repo has had a single (non-pre) release, but.. the impact for my company is that our **users that use Refined GitHub cannot see _any_ release notes because they cannot see any releases of packages that have not hit 1.0 yet.**  Note that this also applies to repos that tag releases but don't use the GitHub release feature.

### How to replicate the issue + URL

https://github.com/bufbuild/connect-es does not show any releases, yet https://github.com/bufbuild/connect-es/releases demonstrates that there are indeed releases (just, pre-releases only because it's still v0.x.x).

Note that this also means that repos that tag releases will have those releases hidden: e.g. https://github.com/pillarjs/send (which has 31 million weekly downloads despite being versioned 0.18.0).  Here's another with 60 million weekly downloads that's the same: https://github.com/ashtuchkin/iconv-lite/releases; and 45 million: https://github.com/gkz/levn/releases, etc.

### Extension version

23.3.2

### Browser(s) used

Chrome

**Comment by fregante** [comment]
Until 2021, GitHub showed releases and tags on the same page, so our tab used to count both. 

When they changed, they started also showing and counting releases on the Code tab, but the count didn't match because it did not include tags:

- https://github.com/refined-github/refined-github/issues/6130

We can't undo this, but I think we should consider adding a Tags tab when releases are missing entirely. I occasionally end up on repositories that don't use releases, but only tags.

**Comment by fregante** [comment]
Closing in favor of:

- https://github.com/refined-github/refined-github/issues/6517
