### ISSUE TITLE
`add collapsible content` doesn't work with browser-ext-github-monaco

### ISSUE THREAD

**Issue by tjx666** [refined-github/refined-github#6410]
### Description

There is another very usefull extension https://github.com/hediet/browser-ext-github-monaco which introduce powerful monaco editor to github.

But `add collapsible content` doesn't work with it.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/224091877-d26261fd-2690-4d20-9575-e519eba12fc7.png">

relatived issue: https://github.com/hediet/browser-ext-github-monaco/issues/47

### How to replicate the issue + URL

1. install https://chrome.google.com/webstore/detail/monaco-markdown-editor-fo/mmpbdjdnmhgkpligeniippcgfmkgkpnf?hl=de&authuser=0
2. open any github issue page
3. click `add collapsible content` button

### Extension version

23.3.2

### Browser(s) used

chrome111

**Comment by fregante** [comment]
Nice extension! I'm pretty sure that this doesn't work because we use `document.execCommand` via [text-field-edit](https://github.com/fregante/text-field-edit) to add content to the field whereas GitHub alters the content directly. The "downside" of the API is that it requires the field to be focusable, but the extension you're using hides it via `display: none`

The good thing is that this can be fixed with some CSS:
```css
textarea:has(+ .hediet-editor-wrapper) {
	display: block !important;
	position: absolute;
	opacity: 0;
	pointer-events: none;
}
```

This should make the editor "focusable but not visible", which fixes it:

![ko](https://user-images.githubusercontent.com/1402241/224100781-2013a16a-9dd1-4c9c-b654-3a623af798f1.gif)

The bad news is that this change doesn't belong to Refined GitHub, so you'll have to paste it into the options.
