### ISSUE TITLE
`sticky-sidebar` cannot be correctly identified as `releases-tab` blocks it

### ISSUE THREAD

**Issue by GideonBear** [refined-github/refined-github#6425]
### Description

All iterations do not make the sidebar sticky, but answering no to each question yields "The change or issue is caused by [warning-for-disallow-edits](https://github.com/refined-github/refined-github/blob/main/source/features/warning-for-disallow-edits.tsx)."
Clicking "Exit" makes the sidebar sticky again.
After further investigation, it looks like when it's determined the feature isn't `releases-tab`, it deactivates that, making `sticky-sidebar` stop working, as the sidebar is too big. This causes it to appear to not be enabled, while it is.

### How to replicate the issue + URL

This happens on every GitHub page where sticky-sidebar works, but doesn't with `releases-tab`, for example https://github.com/PyCQA/prospector.

### Extension version

23.3.2

### Browser(s) used

Chrome 111

**Comment by fregante** [comment]
Thank you for the detailed report, but that's just how `sticky-sidebar` is. Some features are interdependent because they rely on each other's data and state. Another example is the `clean-conversation-sidebar`feature which has the same effect. No much can be done here. Anybody trying to find `sticky-sidebar` would probably search "sidebar" in the filter, and that would work.
