### ISSUE TITLE
Hide newsfeed noise unfold button does not work

### ISSUE THREAD

**Issue by klieret** [refined-github/refined-github#6463]
### Description

The hide newsfeed noise option folds down releases and similar information like so:
![image](https://user-images.githubusercontent.com/13602468/230455803-93d4328e-8496-48ee-af10-4208168711c5.png)

However, the 'unfold button' to the right does not do anything.

Logs:

```
Error: Could not parse repoName from GitHub url: https://github.com/ [repo.ts:92](webpack://sourcegraph/shared/src/backend/repo.ts)
Browser extension is enabled [codeHost.tsx:600](webpack://sourcegraph/browser/src/shared/code-hosts/shared/codeHost.tsx)
SyntaxError: Element.matches: '#dashboard :is(.watch_started, .fork):has(a[href^="/klieret"]),#dashboard .body:has(.watch_started, .fork):has(a[href^="/klieret"])' is not a valid selector 12 [refined-github.js:4953](moz-extension://4db98c48-5dd8-4f6c-b2cd-478fd3054d36/refined-github.js)
SyntaxError: Element.matches: '#dashboard :is(.watch_started, .fork):has(a[href^="/klieret"]),#dashboard .body:has(.watch_started, .fork):has(a[href^="/klieret"])' is not a valid selector 5 [refined-github.js:4953](moz-extension://4db98c48-5dd8-4f6c-b2cd-478fd3054d36/refined-github.js)
```

### How to replicate the issue + URL

**Replicate**: Go to your newsfeed, find release note, click 'unfold' button
**Expectation**: I can see details about the release
**Reality**: Nothing happens

### Extension version

23.3.31

### Browser(s) used

firefox 111.0.1 MacOs

**Comment by fregante** [comment]
This is because Firefox doesn't support the has() selector and there's no other way to target these elements. 

The last related PR:

- https://github.com/refined-github/refined-github/pull/6306

**Comment by klieret** [comment]
Ah, so the intended behavior was to hide both the details and the line we see above? And because firefox doesn't support the selector, it is left over?

Thanks for clearing that up 👍

**Comment by kytta** [comment]
For the future finders of this issue: You can enable `:has()` in Firefox as of today by going to `about:config` and enabling the `layout.css.has-selector.enabled`. **This is not recommended**, as the implementation is still buggy. For example, `hide-newsfeed-noise` will still not work [because of a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1792501).

The alternative fix I am using is just to take the selectors from [hide-newsfeed-noise.css](https://github.com/refined-github/refined-github/blob/567a90067a4d7ad77e463bf4dfd6ffef785cf58f/source/features/hide-newsfeed-noise.css) and create a uBlock Origin filter with it. uBO ships its own implementation of `:has()`
