### ISSUE TITLE
Hide duplicate "Add file" button on new file view

### ISSUE THREAD

**Issue by kidonng** [refined-github/refined-github#6525]
This doesn't make sense:

<img width="1067" alt="Screenshot 2023-04-15 at 22 20 54" src="https://user-images.githubusercontent.com/44045911/232230225-b49d3b95-bf44-4e56-bd11-e0e51b8eca76.png">

If we hide the button on the left, we can also drop this which shortens any remotely long branch name to something unrecognizable:

https://github.com/refined-github/refined-github/blob/3eeda085e745c5b47f104b39edd8fc2cca16ecf6/source/features/default-branch-button.css#L1-L4

Because we will no longer have this bug:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/44045911/232230358-c34087b1-5204-41b6-9d1e-6f7fd91d7270.png">

**Comment by fregante** [comment]
Sounds like an easy feature but this area of the UI is likely under active work so it could be fixed/reworked at any time.

If it's a single CSS rule it could be ok, but I don't see the "Add file" dropdown in some cases, so the left-hand one might still be preferable

https://github.com/refined-github/refined-github/blob/main/.editorconfig

<img width="936" alt="Screenshot 1" src="https://user-images.githubusercontent.com/1402241/232232758-9bd958d8-22dd-4d20-920e-f136c1c067ca.png">

**Comment by fregante** [comment]
I'm ok with the current situation:

- the right-side button is always visible, whereas the left-side one only appears if the sidebar is open
- the left-side one is useful as a quick action

Overall not worth cleaning it up because its DOM is crap, hiding the button leads to:

<img width="314" alt="Screenshot 2" src="https://github.com/refined-github/refined-github/assets/1402241/e6908e8d-2ae0-4041-b0eb-001bac69985c">
