### ISSUE TITLE
`release-download-count` not working on renamed assets

### ISSUE THREAD

**Issue by darkred** [refined-github/refined-github#6727]
### Description

The issue I noticed is that `release-download-count` is not not working in some release pages, e.g.:
```
https://github.com/cli/cli/releases/tag/v2.30.0
https://github.com/cli/cli/releases/tag/v2.29.0
```

But it's working ok in: 
```
https://github.com/cli/cli/releases/tag/v2.28.0
```

If it helps, the non-working pages have 22 assets, while the working one has 21 assets. Screenshots:

<details>
<summary>Non working (22 assets):</summary>

![2023-06-02_215032](https://github.com/refined-github/refined-github/assets/723651/e43f8bf2-cc58-4a9f-9995-b445533eba6b)
</details>

<details>
<summary>Working ok (21 assets):</summary>

![2023-06-02_215042](https://github.com/refined-github/refined-github/assets/723651/5912a89c-6637-4eb6-b907-ffbf75cffad3)
</details>

There are no errors in console.

Note: as mentioned in [here](https://github.com/refined-github/refined-github/issues/6150#issuecomment-1309121829), GitHub allows 100 assets per request, therefore having 22 shouldn't be a problem.
Also, for reference in e.g. `https://github.com/PowerShell/PowerShell/releases/tag/v7.4.0-preview.3` or
`https://github.com/PowerShell/PowerShell/releases/tag/v7.3.4` both with 24 assets it works ok.

### How to replicate the issue + URL

Open https://github.com/cli/cli/releases/tag/v2.30.0

### Extension version

23.6.2

### Browser(s) used

Chrome 114

**Comment by fregante** [comment]
It's not working for either release for me. Could it be that the asset name doesn't match?

<img width="1010" alt="Screenshot 1" src="https://github.com/refined-github/refined-github/assets/1402241/5942b898-205a-4659-b9d7-ab03abcac5ed">


It works well on our repo maybe because we don't rename the assets:


<img width="1047" alt="Screenshot 2" src="https://github.com/refined-github/refined-github/assets/1402241/54d45bf7-6fcd-4d7e-ad75-6ad872b710d9">

**Comment by fregante** [comment]
Judging by your screenshots, the counts appear on the second screenshot because the assets haven't been renamed yet, so that's likely the reason.
