### ISSUE TITLE
Reverse tab open order for `open-all-notifications`

### ISSUE THREAD

**Issue by prettyv** [refined-github/refined-github#6755]
### Description

Currently, when using the "Open unread" button on repositories' notifications tabs are opened in the order they appear in the document, i.e. in reverse chronological order. Especially when following only releases of a repo I'd much prefer tabs to be opened chronologically in release order, and personally feel like that would make sense for other notification types as well.

While I see a change of open order for release notifications as a clear improvement I can imagine it may be more controversial for other notifications? Alternatively, a way to sort the notifications manually - at least for the current page - might be an option? I wouldn't consider a new global feature for reversing notification order as reverse chronological order by default makes sense to me for display.

### Example URLs

https://github.com/notifications

**Comment by fregante** [comment]
> might be an option?

We don't have optional features. All features should make sense as a default.



> a way to sort the notifications manually

It's a can of worms I'd rather not open. Example of issues:

- confusing behavior because it only sorts the current view, unlike how the rest of the website works
- confusing behavior when you mark most notifications as done and new notifications are ajaxed in… appearing at the top 🤔 
- etc


> Reverse tab open order for `open-all-notifications`

I think this makes sense and would as easy as `notificationsArray.reverse()`. PR welcome

**Comment by prettyv** [comment]
Glad to read you think the main idea makes sense, I opened a corresponding PR for it just now.

The manual sort feature was as I was trying to say just an alternative idea in case the simple main one wouldn't have been welcomed, so seems to not need further discussion anyway, but I would have been somewhat unsure about the potential for confusion there as well. I'm aware that optional features aren't a thing here and wasn't what I intended the phrase "might be an option" to mean (to my knowledge that's just a common way of saying "another thing one could do instead", not a native speaker).
