### ISSUE TITLE
Drop `edit-readme`

### ISSUE THREAD

**Issue by 134130** [refined-github/refined-github#6859]
### Description

`edit-readme` is no longer works and needs since new GitHub's UI provides edit buttons for README.md and License file also.

<img width="666" alt="image" src="https://github.com/refined-github/refined-github/assets/50487467/25288d83-1cac-4965-b75e-ed092d1236cc">

### Example URLs

https://github.com/refined-github/refined-github

**Comment by fregante** [comment]
Note that edit-readme only complements that button because GitHub doesn't show it in all cases. See the feature's history. I don't know if they fixed that

**Comment by fregante** [comment]
https://github.com/refined-github/refined-github/blob/e83de1c01249cf6087668f291bcf82d70b0a6422/source/features/edit-readme.tsx#L14

**Comment by fregante** [comment]
The issues still exist.


### Native button exists

https://github.com/refined-github/refined-github

![image](https://github.com/refined-github/refined-github/assets/1402241/3c981038-bca2-43b5-8874-c27b804f94fe)

### Native button missing (`edit-readme` broken on new view

https://github.com/refined-github/refined-github/tree/23.8.24

![image](https://github.com/refined-github/refined-github/assets/1402241/2634e38b-044d-48f4-af2c-72c8e53dfa18)

### Considerations

I might reconsider its utility. Allowing the user to edit files even when they're on permalinks seems useful but maybe it's confusing because the user is redirected to the default branch. Maybe a permalink should look permanent. 

Thoughts on dropping the feature? The same action is still available by clicking `default-branch-button` first, which is more explicit.

**Comment by 134130** [comment]
I think when clicking `edit-readme` on "some" branch, The edit page for readme file on "some" branch should be appeared.
But.. I think is editing docs for specific branch is not common case, so no needed

**Comment by fregante** [comment]
That part already works natively 

- https://github.com/refined-github/refined-github/tree/delete-me
