### ISSUE TITLE
Suggest remove `sync-pr-commit-title` and use out-of-the-box feature on GitHub

### ISSUE THREAD

**Issue by woochanleee** [refined-github/refined-github#6888]
In https://github.com/refined-github/refined-github/pull/423, `sync-pr-commit-title` feature added. But GitHub implemented similar feature on 2022-08-23. https://github.com/refined-github/refined-github/issues/276#issuecomment-1225179479

So I think this feature has the potential to conflict with GitHub. Below you can see, if a single commit the PR title is not changed, even if the merge commit option is selected. I was expecting it to be "Merge pull request #5 from woochanleee/d".

https://github.com/refined-github/refined-github/assets/48552260/0d4c48a2-caa9-446b-a9bf-7b74988d2c0c

<img width="833" alt="image" src="https://github.com/refined-github/refined-github/assets/48552260/644c8e22-b1cc-449c-94f1-9649c58b28f5">

**Comment by fregante** [comment]
I can't find where we had this conversation, but it was decided to leave the feature because it's a global configuration rather than being per-repo like GitHub's. No one wants to go through every repo and configure it that way. 

As for the conflict you mention, it shouldn't happen, also because we specifically don't touch merge commits in the first place. It sounds more like an issue in that the field is set *and then* you switch to a merge commit. 

It might be worth opening a bug report for that.

**Comment by woochanleee** [comment]
@fregante Sorry, i asked a question using a [template](https://github.com/refined-github/refined-github/issues/new?assignees=&labels=under+discussion&projects=&template=3_discussion.md) and the [under discussion](https://github.com/refined-github/refined-github/issues?q=is%3Aopen+label%3A%22under+discussion%22+sort%3Aupdated-desc) label was added automatically. 

I'wll be opening a bug report as soon.

**Comment by fregante** [comment]
No worries, your main request here was in the correct type. But the bug is something we can look at separately.

**Comment by fregante** [comment]
Found the last discussion, for future reference (it contains the same explanation)

- https://github.com/refined-github/refined-github/issues/5155#issuecomment-1336216986
