### ISSUE TITLE
Create a new fork: Description should be filled with "🔀 This is a fork to send pull requests"

### ISSUE THREAD

**Issue by koppor** [refined-github/refined-github#6891]
### Description

When clicking on "Fork", GitHub opens a page and fills in the repository description as default:

![image](https://github.com/refined-github/refined-github/assets/1366654/629776e8-5cff-4266-8603-1d7779f8881a)

I would like to have following text filled in

    🔀 This is a fork to send pull requests

For users not having any extension installed (or turned off the filtering of forked projects), this would make it easer to know which repositories are "original" and which ones are "just" a fork.

### Example URLs

https://github.com/nbbrd/heylogs/fork

**Comment by fregante** [comment]
Fork repositories are already marked as such by GitHub everywhere on the website. It's not necessary to mark your own fork, also because most forks are not marked this way and are created automatically by GitHub when you edit a file on a random repo.

<img width="1105" alt="Screenshot" src="https://github.com/refined-github/refined-github/assets/1402241/c63955d4-7c56-493f-8d4c-31ff64af0cd8">
