### ISSUE TITLE
The repo start count on the top is missing - the side shows

### ISSUE THREAD

**Issue by sedghi** [refined-github/refined-github#6961]
### Description

I know about the pinned issue, and I have read it, BUT my **top** star count is missing

![CleanShot 2023-09-26 at 08 48 44](https://github.com/refined-github/refined-github/assets/7490180/12495015-ba96-4f66-9523-59b307f75166)

### How to replicate the issue + URL

https://github.com/refined-github/refined-github

### Extension version

23.9.21

### Browser(s) used

Version 116.0.5845.187 (Official Build) (arm64)

**Comment by slorber** [comment]
See 
- https://github.com/refined-github/refined-github/pull/6941 
- https://github.com/refined-github/refined-github/issues/6940

@fregante may I suggest to make the description of this option clearer?


Because I expected to find how to disable it by searching for "star" or "fork", and couldn't. That's why I also asked there.


<img width="517" alt="CleanShot 2023-09-26 at 16 22 16@2x" src="https://github.com/refined-github/refined-github/assets/749374/583be267-157e-4657-86dd-9b46db26603d">

**Comment by sedghi** [comment]
I have disabled it but still no stars besides the repo name

![CleanShot 2023-09-26 at 10 50 58](https://github.com/refined-github/refined-github/assets/7490180/05f09257-4d63-4cd2-b7f6-f9db495c57f1)

Let me be clear, I'm fine with duplication of the stars on the side and header. The whole purpose of the start count (which was originally [proposed by me](https://github.com/refined-github/refined-github/issues/6798)) was to show the stars on each repo page.
