### ISSUE TITLE
`select-notifications` - Add filter for Discussions

### ISSUE THREAD

**Issue by rdtechie** [refined-github/refined-github#6980]
### Description

We use Discussions at our organization. As such we get many discussions in per day. I'm aware GitHub is working on their new GUI redesign, but till then I think it's handy if we can get a filter option here for "Discussions":

![image](https://github.com/refined-github/refined-github/assets/6579452/69b30265-e80c-45c5-9eb8-ba959b47f07e)

### Example URLs

https://github.com/notifications

**Comment by fregante** [comment]
I'm sure similar additions were requested for the feature, but I cannot find them at all. 

Anyway I think the best we can do is "Everything else", so that we don't have to extend the list. I think these are the other types that were requested:

- deployment notifications
- release notifications 
- commits I think also occasionally appear there
