### ISSUE TITLE
`locked-issue` - Showing everything as locked on Enterprise Github

### ISSUE THREAD

**Issue by Johannes-Andersen** [refined-github/refined-github#7063]
### Description

It seems like the new locked issue icon introduced here: https://github.com/refined-github/refined-github/pull/7051 does not work as expected on github enterprise

All issues and PRs show as locked, even when they aren't 

![Screenshot 2023-11-15 at 14 02 34](https://github.com/refined-github/refined-github/assets/57638117/0f904959-c9ca-4db0-b96b-db6a752af914)
![Screenshot 2023-11-15 at 14 05 19](https://github.com/refined-github/refined-github/assets/57638117/8f9f2cb4-2577-45ec-98a2-1f23d8d72141)
(both images have the PR and Issue details hidden to not show internal information)

Server:
GitHub Enterprise Server 3.8.11

### How to replicate the issue + URL

https://github.<enterprise_url>.io/<org>/<repo>/pull/<pr>
https://github.<enterprise_url>.io/<org>/<repo>/issues/<issue>

### Extension version

23.11.15

### Browser(s) used

Chrome - 119.0.6045.159

**Comment by fregante** [comment]
Thank you for the report. You can temporarily disable the feature in your Refined GitHub options, selecting your GHE domain

**Comment by fregante** [comment]
I'll release a new version just for this

**Comment by fregante** [comment]
It will be fixed in `23.11.15.1433`, available soon. Here some live badges with the latest version on each store:



[link-chrome]: https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf 'Version published on Chrome Web Store'
[link-firefox]: https://addons.mozilla.org/firefox/addon/refined-github-/ 'Version published on Mozilla Add-ons'
[link-safari]: https://apps.apple.com/app/id1519867270 'Version published on the Mac App Store'

[<img src="https://raw.githubusercontent.com/alrra/browser-logos/90fdf03c/src/chrome/chrome.svg" width="48" alt="Chrome" valign="middle">][link-chrome] [<img valign="middle" src="https://img.shields.io/chrome-web-store/v/hlepfoohegkhhmjieoechaddaejaokhf.svg?label=%20">][link-chrome] 

[<img src="https://raw.githubusercontent.com/alrra/browser-logos/90fdf03c/src/firefox/firefox.svg" width="48" alt="Firefox" valign="middle">][link-firefox] [<img valign="middle" src="https://img.shields.io/amo/v/refined-github-.svg?label=%20">][link-firefox]
