### ISSUE TITLE
Files tab on PRs has become extremely sluggish

### ISSUE THREAD

**Issue by jplatte** [refined-github/refined-github#7085]
### Description

Since one or two days, when reviewing PRs, the browser tab I'm reviewing in becomes extremely unresponsive, both when scrolling (especially on large PRs) but also when clicking the plus icon to attach a new review comment to the diff and when actually submitting the review comment. Things hang for approximately two full seconds for opening the review dialog on the attached URL. This does not happen with the extension disabled.

### How to replicate the issue + URL

- Go to https://github.com/matrix-org/matrix-rust-sdk/pull/2826/files
- Try to attach a review comment

### Extension version

23.11.15.1433

### Browser(s) used

Firefox Nightly 121.0a1 (2023-11-15) (64-bit)

**Comment by fregante** [comment]
You're using Firefox Nightly, we can't really investigate nor support any weird behavior that happens just there.

The Files tab is generally very slow because GitHub loads the entire diff.

Refined GitHub hasn't had a release in 7 days and I don't see anything related to that page, other than https://github.com/refined-github/refined-github/pull/7033 (which only acts after a click)

**Comment by fregante** [comment]
Yes, as long as you ensure it actually isn't natively slow (ie without Refined GitHub)

**Comment by lydell** [comment]
@jplatte You might want to follow https://github.com/refined-github/refined-github/issues/7116
