### ISSUE TITLE
Description "diff" view when editing descriptions

### ISSUE THREAD

**Issue by janpio** [refined-github/refined-github#7142]
### Description

A bit of a crazy idea: 

Instead of just having `Write` and `Preview` when editing a GitHub issue, one could have another tab `Diff` that shows a markdown diff or additions/deletions of the description text. 

That would mostly fit for use cases where one updates an issue multiple times, over a longer period of time of course. I for example had this idea when I added some new features to https://github.com/prisma/prisma/issues/3108.

### Example URLs

https://github.com/refined-github/refined-github/issues/new?assignees=&labels=enhancement%2C+under+discussion&projects=&template=2_feature_request.yml
https://github.com/prisma/prisma/issues/3108

**Comment by fregante** [comment]
You're right that this would be useful, but I see a few complex parts that make this feature out of scope for Refined GitHub:

- we'd have to add a diffing library to Refined GitHub
- we'd have to either also add a markdown parser to render your comment nicely or just display raw text
- we'd have to hack a React widget to add a third unexpected state to the view

And the most annoying/complex of all:

- to ensure that the diff is up to date, we'd need to fetch the latest version of the comment via API, because what we see in the DOM might not be the real "previous" content


So it breaks several of my no-no's for Refined GitHub:

- no diff lib
- no markdown lib
- no extra views

**Comment by janpio** [comment]
True.

I was just thinking "It's in the PR view, so we can just use it" but of course that is not _really_ true.
