### ISSUE TITLE
`conversation-links-on-repo-lists` is redundant on organizations

### ISSUE THREAD

**Issue by Katsute** [refined-github/refined-github#7173]
### Description

Links are redundant on old org repo list, GitHub already includes them:

![image](https://github.com/refined-github/refined-github/assets/58778985/b22d9935-7a4b-450a-9f24-394fde66b7f2)

Links also not needed on feature preview (feature does nothing, no change needed here):

![image](https://github.com/refined-github/refined-github/assets/58778985/31572f83-edca-4cbc-994d-3f41c51a9107)

Links are still needed for users:

![image](https://github.com/refined-github/refined-github/assets/58778985/e49764e8-43f3-4aec-8d6e-2a6426ac5eef)

### How to replicate the issue + URL

https://github.com/orgs/microsoft/repositories

### Extension version

23.12.1

### Browser(s) used

Google Chrome

**Comment by fregante** [comment]
It feels like this was reported before 🤔

**Comment by Katsute** [comment]
I don't see any existing issues on this

https://github.com/refined-github/refined-github/issues?q=%22conversation-links-on-repo-lists%22

![image](https://github.com/refined-github/refined-github/assets/58778985/497c69ba-d0ce-44ed-afa1-c337e88af313)

**Comment by fregante** [comment]
It was mentioned before the feature was even added:

- https://github.com/refined-github/refined-github/issues/1130#issuecomment-549547269

Likely a regression caused by:

- https://github.com/refined-github/github-url-detection/pull/170

I should revert to using `isUserProfileRepoTab` and add a note regarding this issue
