### ISSUE TITLE
`sort-conversations-by-update-time` rewrite labels url, making it difficult to get the original one to copy and add in a message

### ISSUE THREAD

**Issue by Porkepix** [refined-github/refined-github#7205]
Writing with this template even though I don't know if it's the most appropriate and if that would b considered as a bug, a feature request, or none of these.

GitHub now allows to link in a visible ways labels belonging to the same repo. This take the following form: `https://github.com/org/repo/labels/mylabel` and is shown the same way we see labels everywhere.

You can use this kind of url to render the label in a message, but first you need to find that url. These urls lead to the issues using this label.
But it appears that when `sort-conversations-by-update-time ` option is enabled, these urls are rewritten to something like `https://github.com/org/repo/issues?q=is%3Aopen+label%3A%22mylabel%22+sort%3Aupdated-desc`. These urls doesn't render the same way in a message. So while the rewrite is a normal result of this option to achieve its goal, it have this side-effect.

Maybe some possible way to make it better would be a "copy url to this label" button beside every label at the very least on the page listing every label of the repo.
Maybe it's in actually an intended behavior to achieve the goal of the option.

**Comment by fregante** [comment]
It'd be great to use real URLs when posting here, so that I understand what you're talking about, like this:

https://github.com/refined-github/refined-github/labels/ajax

New feature, neat!

I felt the need to disable Refined GitHub before just to get that exact clean URL, I suppose now there's a real drawback to _not_ using it.

Unfortunately there's no easy way to both have `sort-conversations-by-update-time` enabled _and_ get that clean URL. We can somewhat fake it in some cases, but I'm generally against the idea of showing the wrong content for the same URL (e.g. if I send `https://github.com/refined-github/refined-github/issues` to someone and they don't see the same issues I see)

A compromise here would be to clean the URL in the comment fields before sending it, similarly to how we do it with `prevent-link-loss` — but even that sounds like so much trouble for a rare operation with relatively little improvement.

**Comment by fregante** [comment]
If you can track down the feedback form for this feature, maybe we can just ask them to support `?q=` links too

**Comment by fregante** [comment]
We can try changing the URL just in time, at the expense of breaking "right click -> open in new tab". For example here:

https://github.com/refined-github/refined-github/blob/0aa661be9eb59620576eb4f41759863afe9c2a12/source/features/sort-conversations-by-update-time.tsx#L25-L29

We could add a:

```js
if (isLabelLink(link)) {
  await oneEvent(link, 'click', {filter: event => event.which < 2})
}
```

**Comment by Porkepix** [comment]
I resurface after so much time as I quite rarely needs the feature, but I fail to catch how I should be able to reproduce the example given in the linked PR, that should allows me to copy the correct link? (Unless some things changed for the addon in the past almost two years…)

The same way, the linked issue and its linked PR seems to mention a way to reload a tab with GitHub Refined disabled.
It seems we can only disable it from the addon icon if added to the general toolbar. Maybe it could also be added on the irhgt-click menu, alongside the `Reload` entry already there?

**Comment by fregante** [comment]
GitHub themselves broke the feature. It doesn't work even if you disable Refined GitHub. By "it doesn't work" I mean that label links never `/label/` anymore 🤦‍♂️ so GitHub's label links renderer is only hit if you type the URL manually. 

As for what you're asking, no we're not going to add a menu item outside the toolbar icon. This action is not taken that frequently to justify that.
