### ISSUE TITLE
Button link gives the extension full access to the page when clicked.

### ISSUE THREAD

**Issue by Malix-off** [refined-github/refined-github#7229]
### Description

Clicking the extension "button link" (extension icon) gives the extension permanent full access to the domain when clicked, and make the extension be marked as "Access Requested" on any URL.

### Possible Solution

1. Remove the "button link"
2. Make "button link" be a feature _(and consider it being disabled the default)_ that will actually remove the extension being marked as access requested (I don't know if it's possible)

### How to replicate the issue + URL

Anywhere

### Extension version

24.1.10

### Browser(s) used

Google Chrome Version 120.0.6099.225 (Official Build) (64-bit)

**Comment by fregante** [comment]
Unfortunately that's the choice of wording Chrome decided to give. A lot of extensions that don't already have access to the current tab, can gain access if you click their icon, by design. This is because if you click the button you very likely want the extension to interact with the current tab.

For Refined GitHub's case, we have that access because you can enable Refined GitHub on other domains in order to support GitHub Enterprise. See: https://fregante.github.io/webext-permission-toggle/?name=Refined+GitHub&icon=sss

**Comment by Malix-off** [comment]
@fregante 

Can it be a disable-able feature, then?

Moreover, the enabled extension does consume memory even after all github tabs has been closed
<img width="1253" alt="image" src="https://github.com/refined-github/refined-github/assets/76160668/98e2cc41-7d6e-44e2-badf-238d31c7d51e">
