### ISSUE TITLE
`update-pr-from-base-branch` button should allow one to default to rebase

### ISSUE THREAD

**Issue by eax-rippling** [refined-github/refined-github#7270]
### Description

It should be possible to change this button to default to "rebase" instead of "merge".   Similarly it should be clearer that this button will generate a merge commit:
![image](https://github.com/refined-github/refined-github/assets/144721488/73c2cbb2-167d-4ea2-9e61-b4b772a7449a)

### Example URLs

`https://github.com/<org>/<repo>/pull/208131`

**Comment by fregante** [comment]
> It should be possible to change this button to default to "rebase" instead of "merge".

The [API](https://docs.github.com/en/rest/pulls/pulls#update-a-pull-request-branch) only allows merge commits. 



> Similarly it should be clearer that this button will generate a merge commit:

The button label matches the native one, which uses "Update branch" for "create merge commit" and "Rebase branch" otherwise 


<img width="324" alt="Screenshot 11" src="https://github.com/refined-github/refined-github/assets/1402241/a49e662d-60fc-4732-a014-b4efc2d012e3">


<img width="334" alt="Screenshot 10" src="https://github.com/refined-github/refined-github/assets/1402241/9cb20ccf-c199-48f9-b826-9ef6b6298c79">

**Comment by fregante** [comment]
The dropdown in your screenshot is provided by GitHub, not this extension. 

> I'm just asking to be able to change the default option on the button 

Refined GitHub doesn't provide options, so changing the default isn't possible unless it's "better", and not just different.

**Comment by pmcgaley** [comment]
gah. This was the github annoyance I was hoping this extension was going to solve for me. Shame
