### ISSUE TITLE
How often does a change to GitHub break something in Refined GitHub?

### ISSUE THREAD

**Issue by ScottArbeit** [refined-github/refined-github#7351]
Hi! 

I work at GitHub, on our Revenue team, and I get to work with some of our large enterprise customers. I know that some of them have created their own in-house browser extensions to customize their GitHub experience in ways that maybe don't make sense for the broader customer base, and a customer I work closely with just asked me today about creating one.

I was wondering: how often do changes to the GitHub UI cause breaks in Refined GitHub? My completely anecdotal (and maybe naive) impression is that GitHub is conservative in making major UI changes, given the breadth of customers we serve, so I hope the answer is: "not very often," but I figured asking in a repo with 23K stars and 3700+ commits is the fastest way to get a real answer.

Is it painful to keep with our UI changes?
Is it not too bad?
Is there a way that you track the changes that might be coming, or is it more of a reactive effort to make fixes after we release a change?
Are there areas of the UI that change faster than others?

I'd love your feedback. To be clear, I'm not here as any sort of officially reaching out, but I will circulate this issue internally so there's some awareness of what it looks like from the outside.

Thanks!

**Comment by fregante** [comment]
Over the years GitHub has been pretty stable, generally breaking a host of feature about twice a year, while there's a random breakage every couple of months. The former happens when they rewrite a whole view or rename the classes. 

However in the past couple of years we've been seeing more React components that are difficult to target and update correctly. With transitional PJAX the old DOM (and our edits) would disappear and then a "load" even would be fired; with React views (specifically the file/folder views) are now SPAs that update only what's necessary and are hard to select (e.g. no classes or generated classes)

**Comment by fregante** [comment]
For the other specific questions:

> Is it not too bad?

The file/folder view features have been essentially broken for Refined GitHub for a year because they only apply on the first load, not on SPA update. 


> Is there a way that you track the changes that might be coming, or is it more of a reactive effort to make fixes after we release a change?

Reactive. If GitHub launches a beta version first we have a chance to review and get ready for it. If not, we wait for the bug report.
