### ISSUE TITLE
Open all unread notifications from any page

### ISSUE THREAD

**Issue by bo0tzz** [refined-github/refined-github#7442]
### Description

I find myself using the "Open all unread" button on the notifications page pretty much exclusively. It would be great to have a way to directly access that functionality from any page, for example by alt-clicking the notifications button in the top right.

### Example URLs

https://github.com/

**Comment by fregante** [comment]
I like this and it's potentially easy to implement (click handler -> API request -> open tabs -> show toast), the problem is where to put this exactly.

Hiding it behind "alt-click" means most people won't see it, and it's relatively too complex for feature that nobody sees. Adding an extra button is also problematic because the UI is regularly out of date, but maybe that's not too bad

**Comment by fregante** [comment]
Partial mockup for a button: 

<img width="263" alt="Screenshot 3" src="https://github.com/refined-github/refined-github/assets/1402241/0751c0e7-e70e-4dd6-a15f-856a8d48ab91">

I feel that this feature would actually be quite useful for all people who _don't_ have too many unread notifications. It would still prompt the user before opening too many tabs though:

https://github.com/refined-github/refined-github/blob/ad0054477020c52e7140278200be00fc764cc469/source/helpers/open-tabs.ts#L13-L16

**Comment by fregante** [comment]
Easier yet would be if we just move the indicator to the side somehow and then handled clicks specifically on it. Quick mockup:

<img width="249" alt="Screenshot" src="https://github.com/refined-github/refined-github/assets/1402241/32d41f7f-7063-4ddc-bab6-2df7757fc337">

This would be easier to keep in sync because the JS part would be a simple `delegate` event listener.

**Comment by bo0tzz** [comment]
I like it! I would be a little worried about accidental clicks, but maybe that could be mitigated by lowering the threshold for the `window.confirm()` call? (Or maybe it's fine). And then I'll adapt my alt key suggestion to bypass that confirm call entirely, just like in the quick-review feature ;)

**Comment by fregante** [comment]
I want this feature yesterday. I agree that for people who don't have a lot of notifications it's exactly what they do anyway:

1. Open notifications
2. Open all unread

I still think this would still be a better option if you use Chrome/Firefox though: https://github.com/tanmayrajani/notifications-preview-github

Apple makes it difficult to publish Safari extensions so I stopped working on that extension.

**Comment by alexandrosandre** [comment]
Yes please!

BTW: I lost the button today 😨 . What happened?!

**Comment by fregante** [comment]
Refined GitHub is already available for Safari and is published by Sindre Sorhus

**Comment by bo0tzz** [comment]
Incredible, thank you!
