### ISSUE TITLE
Does not appear in search for Firefox Android

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7486]
Empty:

- https://addons.mozilla.org/en-US/android/search/?q=refined

But the Android-specific link works: 

- https://addons.mozilla.org/en-US/android/addon/refined-github-/

This is what I see in the developer hub on AMO:

<img width="739" alt="Screenshot 6" src="https://github.com/refined-github/refined-github/assets/1402241/96d0bf54-1c72-4006-b19a-cc1d3e7d79d3">

Continues from:

- https://github.com/refined-github/refined-github/issues/6367

Related:

- https://github.com/refined-github/refined-github/pull/7480

**Comment by diox** [comment]
Hi, I work on AMO - This is a quirk caused by accessing https://addons.mozilla.org/en-US/android/search/?q=refined with a non Firefox for Android browser. AMO tries to detect your browser and version to only show you relevant add-ons, but if you're forcing `/android/` while on desktop or on Android without Firefox, it doesn't know for sure what version to aim for, and so it picks `120.0` at the moment. Your extension is only compatible with 121.0 or higher so the API excludes it from the results.

If you check out that URL from a Firefox for Android >= 121.0 browser (either a real one or overriding your UA with Firefox's Responsive Mode, for instance), it should work fine.

**Comment by INSANEMODE** [comment]
Can confirm that it works on Firefox for Android 128.0
![Screenshot_20240624-080937.png](https://github.com/refined-github/refined-github/assets/10606102/20ba1ce2-abcf-4a0f-86d1-03b97e9aba02)

**Comment by fregante** [comment]
Great to hear! Thanks for the comment
