### ISSUE TITLE
Firefox shows about:blank tab when doing certain actions on github

### ISSUE THREAD

**Issue by CommanderRedYT** [refined-github/refined-github#7521]
### Description

When navigating github, on some repositories it just freezes / breaks the tab. Actions that depend on JS do not work anymore and sometimes the tab breaks so much that firefox displays it with about:blank in the url bar.
Also, for some reason dark reader breaks when this bug happens.

### How to replicate the issue + URL

1. Visit https://github.com/OpenDTU-App/opendtu-react-native
2. Click on issues. Nothing happens.
3. Click on another thing that depends on JS like the code dropdown button. Nothing happens.
4. When now clicking on a link, the url in the bar switches to `about:blank`.

### Extension version

24.7.1

### Browser(s) used

Mozilla Firefox 127.0.2

**Comment by fregante** [comment]
Does it lock up the tab? Is the CPU at 100%?

**Comment by CommanderRedYT** [comment]
Only the JS parts stop working. CPU is not at 100%. I can still close the tab, so it is different than with other times I experienced tabs crashing. When I close it and use the re-open tab feature of firefox, sometimes it works after that.

**Comment by fregante** [comment]
Version 24.7.11 included some improvements that affect page change performance, especially in Firefox. 

- https://github.com/refined-github/refined-github/pull/7513
- https://github.com/refined-github/refined-github/releases/tag/24.7.10

Since there haven't been any reports, comments, reactions, I can't repro, and this new version is out, I'm going to close this for now.

I hope that with Firefox 128 and the latest 24.7.23 (still being deployed) you won't experience this issue anymore
