### ISSUE TITLE
Not compatible with latest firefox-ESR ?

### ISSUE THREAD

**Issue by HakaishinShwet** [refined-github/refined-github#7528]
i am new user and unable to install this in latest firefox ESR. Is it completely not supported or issue with latest version? And if no support for firefox ESR then may i know the reason for it? Many doesn't want too frequent updates so they use ESR most stable version and every possible thing simply works in it so i hope there is a valid reason if it is not supported for ESR

**Comment by fregante** [comment]
> Is it completely not supported

Correct, the minimum version is 121


> may i know the reason for it?

The reason is that Firefox is always unreasonably late to catch up with other browsers, so a required/useful feature is v121+:

- https://github.com/refined-github/refined-github/issues/5797

> every possible thing simply works in it

That's by definition not correct because v115 (ESR) does not have features that v121 has. 

In any case, you're lucky because the next ESR (v128) is only 3 days away:

https://whattrainisitnow.com/calendar/

**Comment by fregante** [comment]
You could also install v24.4.9 in the meanwhile, which is the last version with Firefox v120- support. Then the browser will update to the latest version once you update your ESR. 

You can find it on https://addons.mozilla.org/en-US/firefox/addon/refined-github-/versions/
