### ISSUE TITLE
Show number of disabled features on extension options page

### ISSUE THREAD

**Issue by injust** [refined-github/refined-github#7550]
### Description

<img width="712" alt="Screenshot 2024-07-15 at 7 11 01 PM" src="https://github.com/user-attachments/assets/eb1cd49b-2841-44ad-a644-71220fcdc856">

could look like

<img width="707" alt="Screenshot 2024-07-15 at 7 11 19 PM" src="https://github.com/user-attachments/assets/f19f0027-2724-4920-9fe5-60ba8ea2df2d">

### Example URLs

chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/assets/options.html

**Comment by fregante** [comment]
That number is actually an approximation because it also includes a CSS features, both standalone and small fixes in refined-github.css

Since being exact with this count would make it verbose, I'd rather not, also because I hope people won't disable more than handful anyway.

**Comment by injust** [comment]
Your explanation makes sense! I don't want to complicate things just for this minor change.

Just some colour for why I requested this:

I recently installed the extension, and occasionally want to compare a Refined GitHub feature to the original behaviour. There's a few ways to do this:
1. Disable all the features from the extension options (this takes a few clicks because the button is hidden under "Identify feature" and then "Toggle all features...", which also makes it a bit hard to find)
2. Disable the extension entirely (this is unfortunately what I ended up doing, but it works!)
3. Use the Identify feature button (the binary search is awesome, but way too many clicks for this simple purpose)

When I was still doing 1), sometimes I would forget if I had re-enabled all the features. So I'd go into the extension options to check...but there's no visual feedback for that. So I'd just click those 4 buttons again to make sure all the features were enabled.

**Comment by fregante** [comment]
"Toggle all features" is hidden specifically because it's the nuclear option and it has drawbacks like these. I don’t think adding a counter would be beneficial here. 


I think every variation of that is already possible:

- you want to see the whole native GitHub: 
  - you disable the extension and re-enable it; It already works, it requires no effort on our part, and it's completely safe (no configuration loss like you get with point 1)
- you want to see the native version of single feature: 
  - you disable the single feature
- you don't know what's affecting the page: 
  - disable the extension
  - use "identify feature"

**Comment by fregante** [comment]
Reopening, the counter can be implemented for the number of features disabled (including hotfixes)

> Features: 216 (1 off)
