### ISSUE TITLE
Shortcut for striking through multiple lines at once

### ISSUE THREAD

**Issue by edeesis** [refined-github/refined-github#7790]
### Description

Github supports the ability to surround text with a tildes by highlighting and hitting the tilde key which strikes them through.

However, when you do this with multiple lines, it simply adds a tilde to the beginning and end of the selection.

This becomes really annoying when dealing with multiple text lines and wanting to cross through them all - you have to select each line individually.

While this is something that Github could support, there isn't a lot of movement on related discussion topics like https://github.com/orgs/community/discussions/5248

### Example URLs

Anywhere there's editable text, pull request bodies, comments.

**Comment by fregante** [comment]
> hitting the tilde key

That's actually a Refined GitHub feature: `one-key-formatting`.

Supporting multiple lines is a little difficult because you have to intelligently detect where to place the formatting character. For example:


```md
# title

paragraph

1. item

![image]()
```

wouldn't be:

```md
~~# title~~
~~~~
~~paragraph~~
~~~~
~~1. item~~
```

but:


```md
# ~~title~~

~~paragraph~~

1. ~~item~~
```

Considering we're using an external helper to wrap the selection (because it's not easy to do), I don’t think it's worth bringing that logic in-house _and then_ parse Markdown, sadly.
