### ISSUE TITLE
Toggle or copy button to make diff signs unselectable in `diff` and `patch` code blocks

### ISSUE THREAD

**Issue by karlhorky** [refined-github/refined-github#7805]
### Description

Originally there was a discussion in 2019 to leave inline diffs (`diff` and `patch` syntax highlighting in Markdown code blocks) untouched:

- https://github.com/refined-github/refined-github/pull/1866#issuecomment-475528334

Copying multi-line diff lines which have been added or removed to paste in code is still a bit painstaking (needing to remove the `-` and `+` signs from the pasted code).

What are the thoughts around adding one of the two?

1. A toggle button (persistent) to enable / disable copying of all `-` and `+` diff signs
2. A copy button which copies without all `-` and `+` diff signs

### Example URLs

https://github.com/ts-safeql/safeql/issues/199#issuecomment-2356407115

**Comment by fregante** [comment]
Do you have a Mac? Does alt-selecting work in your browser? https://youtu.be/skr8Qah0OYY?t=4m

I have a few issues with this:

- I don’t think it’s a common occurrence, I very rarely see diff blocks that contain real code in comments
- the plus or minus are IMO part of the content and losing them will probably make the subsequent pasting very confusing: what to keep? What to delete?

For `patch` you should be able to paste it in its entirety and have git handle it via something like `git apply-patch <(pbpaste)` (I don’t remember the exact command)

If this operation is frequent for you, maybe there’s a IDE plugin to apply the `diff`, remove the signs, or otherwise simplify the input in the IDE itself.

**Comment by fregante** [comment]
*Maybe* we can add a “hide diff” button that:

- removes the signs
- hides the deleted lines
- updated the copy button to copy this new text

But I’m still on the fence about the popularity/complexity ratio of this proposed feature.

**Comment by karlhorky** [comment]
> Do you have a Mac?

I do, yep!

> Does alt-selecting work in your browser?

No, doesn't seem to work in Chrome (at least not in the code blocks on GitHub)

Good idea though, creating a selection of a rectangular area would solve the issue.

> But I’m still on the fence about the popularity/complexity ratio of this proposed feature.

Ok, makes sense 👍  I understand the reasoning - I could see how it may not be an easy thing to do, and maybe it's not common for a lot of users.

**Comment by fregante** [comment]
> popularity/complexity ratio of this proposed feature
