### ISSUE TITLE
Better logging separation for composite action

### ISSUE THREAD

**Issue by wouter-heerwegh** [refined-github/refined-github#7815]
### Description

Hi,

I was recently playing around with composite actions but found it very annoying to debug when a step fails. It seems like this feature has been requested to github for quite a while, but no response so far on when it might be implement.

A discussion is opened here: https://github.com/orgs/community/discussions/21276

Would it make sense to implement such a feature in refined github?

### Example URLs

https://github.com/refined-github/refined-github/actions/runs/10975180926/job/30474531233

**Comment by fregante** [comment]
This is not something extensions can do

**Comment by wouter-heerwegh** [comment]
Hi @fregante,

Thanks for the feedback, would you be able to elaborate why extensions would not be able to do this? I'm not very experienced with web development.

I thought because the steps of the composite action are exposed because of [this issue](https://github.com/actions/runner/issues/1272) (every step is a dropdown and starts with "Run"), that it would boil down to web UI modifications. The extension should not know which steps were skipped or not yet ran, but I guess it could highlight which ones ran successfully.

**Comment by fregante** [comment]
I’ll add a link to an page that actually uses composite actions (your example URL does not):

- https://github.com/refined-github/github-url-detection/actions/runs/10485041597/job/29040451491

What I meant by my previous comment is that GitHub does not expose the necessary data to do what you’re asking. Even if it did, I don’t really want to hack into the runner log component because it’s frequently updated, so it’s difficult to edit and it’s easy to break it.

**Comment by wouter-heerwegh** [comment]
Yeah sorry about that. That's fair. Hope Github implements something for this soon. Debugging pipelines is a pain.

Thanks for the response.
