### ISSUE TITLE
`quick-repo-deletion` - Drop `delete_repo` permission

### ISSUE THREAD

**Issue by fregante** [refined-github/refined-github#7826]
The feature is interesting but it's not worth this scary permission.

We can:

1. Replace the button with a link to https://github.com/:owner/:repo/settings#dialog-show-repo-delete-menu-dialog
2. Automatically open the "Delete repo" dialog when the user lands on the page

This changes the operation from 1 click to 4 clicks + typing the repository name.

I think that last step is no longer necessary as the deletion wizard is already good enough, so we should add one more part to the feature:

- auto-fill the repo name on the last step

**Comment by SuperSandro2000** [comment]
> This changes the operation from 1 click to 4 clicks + typing the repository name.

Can we autofill that or skip some of the clicks? I really liked about the button that it was way faster to delete some forked repo than going to settings and pasting the repo name.

**Comment by fregante** [comment]
Yep see my PR, it’s now autofilled as well. For now that happens only when following this delete fork button

**Comment by devnoname120** [comment]
Data point: I preferred the old behavior. I understand that this enables to use this feature without having a token set up in the settings which some users will find nice.

From my user PoV it's scarier to see Refined GitHub automate the UI rather than have it do an API call because if the page changes bad things could happen (or at least it would break more easily).

**Comment by fregante** [comment]
The old behavior has already been somewhat restored

- https://github.com/refined-github/refined-github/issues/7865
