### ISSUE TITLE
`quick-repo-deletion`: Reintroduce old behaviour

### ISSUE THREAD

**Issue by InSyncWithFoo** [refined-github/refined-github#7865]
### Description

This feature's behaviour was changed in #7826. I understand that this was done to minimize the risk of something going wrong, but it is now way too inconvenient to delete a fork.

* Before: One button click.
* Now:
	* One click to go to the settings with the panel displayed.
	* One click to confirm that I indeed want to delete the repository.
	* One click to confirm that I understand the effects of doing so.
	* One click to submit the form.
	* 2FA authentication; either:
		* One click to send a notice to my phone, then turn it on and tap the notification.
		* Type my password, then one click to submit.

Granted, the last step is only necessary once every two hours, but it is quite rare for me to delete more than one fork in the same day, let alone two hours.

Could the old behaviour be reintroduced somehow? Perhaps via a disabled-by-default feature?

### Example URLs

https://github.com/InSyncWithFoo/some-non-existent-fork

**Comment by fregante** [comment]
Yeah it is definitely a downgrade, but the flow isn't _that_ terrible especially now that I auto-fill a field. You should have your browser save the password. I can definitely have it skip at least one more screen here:

![](https://github.com/user-attachments/assets/4632424f-7d16-46b7-85cc-bb3ad8c063b2)



> Could the old behaviour be reintroduced somehow? Perhaps via a disabled-by-default feature?

It's though because if people don't use it, then it's hard to maintain, which means it's more likely to break—and you don't want a feature with `delete_repo` to break. That's the reason behind it.

The feature had lasted a surprisingly-long time unaltered but GitHub has been in the process of a total rewrite, it seems, and its days were counted.

**Comment by fregante** [comment]
How about this:

1. Add a cltr-alt-click handler on the field
2. Use `confirm()`
3. If missing, tell the user to add `delete_repo` permission for this to work

This means it can be restored safely:

- without fragile timer UI
- without requiring `delete_repo` when creating the token
- avoiding mistaken clicks due to 2 modifiers

The same listener can also be added to the classic "Delete this repository" button in the Settings page of all repos.

Could you send a PR?

**Comment by devnoname120** [comment]
@fregante Would this mean that <kbd>Ctrl</kbd> <kbd>Alt</kbd> has to be pressed whenever I click on delete this fork? Or would it just be for the first time? Alternatively would there be a way to check if the token has the right permission and if so do an API call directly?
