### ISSUE TITLE
Non-rounded corners on native `All | Unread` buttons on Notifications page

### ISSUE THREAD

**Issue by AbhinRustagi** [refined-github/refined-github#7875]
### Description

The [All | Unread] Selection option on the Notifications page has a square border instead of a rounded one. I'm not sure if this is meant. To my knowledge, it is not due any other extension.

![Screenshot 2024-10-09 at 7 14 19 PM](https://github.com/user-attachments/assets/a8e00efe-b25b-4226-b293-8d0c12e001b8)

### How to replicate the issue + URL

[github.com/notifications](https://github.com/notifications)

### Extension version

24.8.20

### Browser(s) used

Firefox

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
Nice catch. Somehow this is a Firefox-only issue. The culprit is:

https://github.com/refined-github/refined-github/blob/54267e2478b1731dd8209402165cd8bcce613a82/source/refined-github.css#L162-L166

Now I want to know why only Firefox is affected. We had a similar Firefox-only issue for that:

- https://github.com/refined-github/refined-github/pull/6475

**Comment by AbhinRustagi** [comment]
I'd need to check where all this style is being applied. But I think changing it to `.BtnGroup-item:not(:first-child)` should do the trick.

**Comment by fregante** [comment]
I think it's Firefox-only only because of the order of CSS injection, not difference in DOM.

The CSS code should be removed or adjusted so it applies only to `default-branch-button`. I think the fix is to add `rounded-left-0` to 

https://github.com/refined-github/refined-github/blob/4cb77df3ccf6da9de3b2427e841ad5d2afa25f35/source/features/default-branch-button.tsx#L37
