### ISSUE TITLE
`align-issue-labels` should also align CI build status

### ISSUE THREAD

**Issue by Andrew6rant** [refined-github/refined-github#7935]
### Description

I think it would look nice if the ✓ and ✗ icons for Actions' PR runs were left-aligned.

Here's a quick comparison between the current `align-issue-labels` and my current userstyle CSS:

![align-issues-extended-pr css](https://github.com/user-attachments/assets/cea144da-5644-40c7-b123-be9e24d5817c)

I also align the tags to the right (as to not add an extra row to each entry), and slide the merge conflict and linked issues buttons near there for better readability.

Here's how the Issues page looks:
![align-issues-extended css](https://github.com/user-attachments/assets/03b38ca5-1708-4594-8808-29cfb447b9d7)

Would any of these be worth PRs (I do make layout changes, but not any more than `align-issue-labels` does already)? And if so, how granular should I split them up?

### Example URLs

https://github.com/refined-github/refined-github/pulls
https://github.com/refined-github/refined-github/issues

**Comment by fregante** [comment]
GitHub is about to introduce changes to that list, so we won't work on it until they're done. Refer to #7856

As for the changes you specified:

- align CI: sounds good
- move labels to the right: they're too far from the title, I think it's a loss in scannability

**Comment by fregante** [comment]
I just checked on the new view: https://github.com/eslint/eslint/issues?q=is%3Aissue%20OR%20is%3Apr

This is no longer possible because:

- they now include extra text next to the checkmark, like `✅ 20/23`
- the line has `overflow: hidden` so moving the checkmark would require enough CSS to make the whole component a bit fickle

<img width="412" alt="Screenshot 19" src="https://github.com/user-attachments/assets/69715708-cb9b-48af-a72c-3b3001652d0e">
