### ISSUE TITLE
Refined github on safari causing errors + page reload

### ISSUE THREAD

**Issue by jni** [refined-github/refined-github#7942]
### Description

I'm seeing errors whenever loading the GitHub notifications view and using refined github. This causes Safari to say "this page was reloaded because of a problem". After enough clicks and archiving of notifications, Safari refuses to load:

<img width="280" alt="Screenshot 2024-10-23 at 3 36 31 PM" src="https://github.com/user-attachments/assets/212f7ab4-b86f-4085-a09d-9ecdf0532521">

I have confirmed that this doesn't happen if I disable refined github, and clearing the cache did not make the problem go away.

### How to replicate the issue + URL

https://github.com/notifications

Console log: https://gist.github.com/jni/ba3dee5baf39a5691f5e4182fd014b5e
Config: https://gist.github.com/jni/ed9112fb59ed6af2d7d0be7f772b0fb7

### Extension version

24.10.1

### Browser(s) used

Safari macOS

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by jni** [comment]
Thank you! 🙏

**Comment by fregante** [comment]
Thanks for the report. I'm aware of this problem and it's actually a browser bug related to selectors, similar to #7252.

In my case, I see the page consistently crashing just as I leave it, which Safari successfully and immediately recovers from, which is why I've never prioritized it.

It would be good to find which selector is causing this and change it, but it takes a lot of page refreshes, sometimes the issue doesn't appear. The bisect feature might be useful here.

It seems that a good repro for the issue is:

0. Open https://github.com/notifications
2. Click "Saved" in the sidebar
3. Click "Inbox"
4. GOTO 1

**Comment by jni** [comment]
Thanks for the context. I have never done any webdev so I will leave this in your capable hands, but just wanted to say, I just switched browsers from Firefox, where I have been using refined github for years, and as soon as I logged into GH I was like OH MY GOD HOW DO PEOPLE WORK LIKE THIS 😂, so I just signed up as a sponsor. Huge thank you for your work!!! 🙏

**Comment by fregante** [comment]
Thank you!

Content blockers don't block scripts from other extensions, and also we don't use polyfills in any capacity. You can actually [find the error in Console.app](https://bugs.webkit.org/show_bug.cgi?id=276942) and it points to selectors specifically, unfortunately it doesn't say which one.
