### ISSUE TITLE
`conventional-commits` broken (by ticket ref?)

### ISSUE THREAD

**Issue by sulami** [refined-github/refined-github#8066]
### Description

I've noticed the other day that conventional commits, both in repo commits and PR commits, and on both old and new (beta) view are broken if there is a ticket reference in the commit subject.

See this example of a positive and negative:
<img width="564" alt="image" src="https://github.com/user-attachments/assets/6647d873-7ac2-4c7b-8e77-ff2e3fc4a313">

### How to replicate the issue + URL

For example, `feat: FOO-123 Implement bar support` does not get the converted badge if `FOO-123` is a ticket reference and thus made into a link.

I would love to include a demo URL, but this happens in my employer's private repository, and the external references (in our case JIRA) aren't linked in public repositories, and the feature requires Pro/Enterprise, which I don't have myself. As a token of effort, here's a screenshot of the source as it appears if an external reference is linked (same commit as above):
<img width="425" alt="image" src="https://github.com/user-attachments/assets/47e5105d-e383-4a01-a9af-9a68dd74ada2">

No console errors, I suspect the changed DOM structure breaks something.

### Extension version

24.11.12

### Browser(s) used

Firefox

### Token ⚠️

- [X] I set a token in the options page. I understand that some features require a token to work.

**Comment by fregante** [comment]
This is somewhat intentional/known:

https://github.com/refined-github/refined-github/blob/d48eecc01e27bf63f623753bd57d02e8463ff3b5/source/helpers/conventional-commits.test.ts#L63

1. We only get the first **text node** specifically to avoid links, so the detected title in your commit is `"fix: "`
2. We also avoid linkifying commits that are _only_ `fix:` because that would look like a title-less commit

A workaround could be:

1. alter `parseConventionalCommit` to correctly parse that string
2. alter `renderLabelInCommitTitle` to skip the element if we confirm that the title is really only `fix:`

https://github.com/refined-github/refined-github/blob/d48eecc01e27bf63f623753bd57d02e8463ff3b5/source/features/conventional-commits.tsx#L18-L24

**Comment by sulami** [comment]
Ah, I see. I had suspected, but not tried, that placing the ticket reference later in the subject would also work, which I from your explanation seems to be the case, as it would generate a longer continuous title.

Thanks for the quick response.
