### ISSUE TITLE
Add a quick navigation tab for Milestones

### ISSUE THREAD

**Issue by llucax** [refined-github/refined-github#8085]
### Description

I would like to have a quick access tab in the top bar to access milestones.

![image](https://github.com/user-attachments/assets/4b1333b5-0962-4769-abc0-8e508f083fac)

This is basically an attempt to reopen https://github.com/refined-github/refined-github/issues/7271, maybe there is a chance it is reconsidered 3.5 years after it was first requested.

I find the reason given to close it ("Milestones are a relatively rarely used compared to what's in the nav bar") not very convincing. I guess it depends on how you are using the repository. For example for me, I access the Milestones much more often than Actions, Wiki or Releases.

I guess you either use milestones or you don't, but if you do, you access them quite often. In any case, users not needing this quick access item can turn it off in the features. It could even be turned off by default if you think the majority of people don't use milestones.

I hope you reconsider :)

### Example URLs

https://github.com/frequenz-floss/frequenz-client-microgrid-python/

**Comment by fregante** [comment]
I think there was a misunderstanding in what was "rare". Out of 100 users, 2 users use something. That's rare. Whether they use it 1000 times daily it doesn't make it any less _rare_ in general.

Since Refined GitHub is a general product, I try not to add features that few people benefit from, particularly if they appear in the main navigation of the main product of GitHub. In fact, Refined GitHub even drops/hides 2 tabs that have likely broader appeal than milestones: `clean-repo-tabs`



> It could even be turned off by default

See https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#2-it-makes-sense-as-a-default-for-everyone

If you need this feature, it's actually quite easy to add create a userscript for it
