### ISSUE TITLE
Environment quality of life improvements

### ISSUE THREAD

**Issue by Netail** [refined-github/refined-github#8166]
### Description

2 feature requests regarding environments;

1. If you are on `https://github.com/<owner>/<repo>/deployments` and select an environment on the left, you only see commit which went life into the environment, but you don't have a shortcut to go to the environment's settings (which are located on `https://github.com/<owner>/<repo>/settings/environments/<environmentId>/edit`). A shortcut could be a nice quality of life feature.
2. The second is bulk deletion of environments on the `https://github.com/<owner>/<repo>/settings/environments` page

### Example URLs

`https://github.com/<owner>/<repo>/deployments`

`https://github.com/<owner>/<repo>/settings/environments`

**Comment by fregante** [comment]
> > 1. you don't have a shortcut to go to the environment's settings (which are located

It's 2 clicks away, we can't add a shortcut to save one click on a rare operation.

<table>
<tr><th>Click 1<th>Click 2
<tr><td>
<img width="318" alt="Screenshot 1" src="https://github.com/user-attachments/assets/b9607b76-e859-4fc8-a83b-521e5f2962d7" />
<td><img width="217" alt="Screenshot 2" src="https://github.com/user-attachments/assets/95c4f0bd-560c-432d-81e2-7cc01d331870" />
</table>



> 2\. The second is bulk deletion of environments on the `https://github.com/<owner>/<repo>/settings/environments` page

Rare batch operations like this one are best done with `gh-cli` rather than via UI. All the big repos I manage have zero or <5 environments, I don’t think a lot of people have many more.

> `https://github.com/<owner>/<repo>/deployments`

Next time please post REAL, clickable URLs as the field suggested.

https://github.com/refined-github/refined-github/deployments not `https://github.com/<owner>/<repo>/deployments`

**Comment by Netail** [comment]
> Next time please post REAL, clickable URLs as the field suggested.

Of which app? These are URLs only accessible by repo maintainers; I could put in my own repo URLs, which won't work for you guys. Or could use refined-github, but are not available for others too and I am not sure if it has any environments at all.

> It's 2 clicks away, we can't add a shortcut to save one click on a rare operation.

On the environments pages in settings, we have 7 pages (100 each), it annoying having to search for the correct env through all pages.
